### ISSUE TITLE
Server crashes on Windows 10: Failed to initialize CEncoder

### ISSUE THREAD

**Issue by GitGitHubUser** [JackD83/ALVR#1]
Hi,
I am getting this error and server crashes:
`Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: This GPU does not support H.265 encoding. (NvEncoderCuda NV_ENC_ERR_INVALID_PARAM)
`
Regardless if I choose H.264 or H.265 - same problem. Please help, thanks.
Windows 10 Pro, 64 bit, Nvidia Geforce 1080 ti.

**Comment by gunnarweibrink** [comment]
Same here... Win10 x64 1903, nVidia RTX2080, Driver 431.70.
Experimental v2 works like a charm!

**Comment by gunnarweibrink** [comment]
Now it works... to be preceise: The error occurs after connecting the device while starting SteamVR.
Nothing else changed but "video resolution" at "Video" tab... from 150% to 100%.
Now it work's as it shoud.

**Comment by JackD83** [comment]
Always update to the latest nvidia driver. If you have a laptop with a nvidia and an intel gpu, you need to disable the intel gpu to get it working
