### ISSUE TITLE
(help) I can't find the head display in LAN. What command should I run to recover

### ISSUE THREAD

**Issue by q1014723373** [JackD83/ALVR#100]
I tried to run the command of independent network (ADB shell am startservice - n "com. Polygraph. Alvr /. Changesettings" -- es "targetservers" "10.10.10.10") but my local area network search didn't show up. Thank you very much

**Comment by orangpelupa** [comment]
it should automatically detect your quest 

- make sure your quest have ALVR v8 apk installed
- try to ping your quest IP address from your PC

**Comment by q1014723373** [comment]
感谢您的任何帮助
