### ISSUE TITLE
Quest does not appear in headset finder

### ISSUE THREAD

**Issue by therf311** [JackD83/ALVR#104]
Hi, I feel like I've tried just about everything I've found elsewhere, but I'd really like to know if there is a solution to this. I've already done a lot of messing with the firewall, ran the add rules as admin, the quest is on the same wifi as the computer, etc. Does anyone have any answers?

**Comment by orangpelupa** [comment]
can you ping your quest from your computer?

**Comment by therf311** [comment]
> can you ping your quest from your computer?
I could, but I ended up just caving and buying Virtual Desktop, then realized my computer isn't good enough to run anything and scrambled to get a refund. Thanks for any help given.
