### ISSUE TITLE
Quest crashes after about 15 minutes of play - no matter what resolution or codec used...

### ISSUE THREAD

**Issue by walterklomp** [JackD83/ALVR#106]
Hi,

What could I do to get the optimal quality and longitivity of the battery?  I am running experimental v8 on an RTX2070S ... Linked to a charger I am playing project cars2. On 30 mbps and HEVC codec I can play for a while longer but eventually it will still crash.
Increasing the speed increases the quality of the video when still on 100% scaling.

When it crashes I first get artifacts and breakage. There is no indication on the server of any packet loss (some fec errors but negligible).  Eventually if I keep on going, the headset will basically freeze up.  The server still gets the position updates, but whatever is projected in the headset is frozen.  To get out of it, ONLY a long press on the power-button works, rebooting the headset.

Also note after a while playing and it didn’t crash, and exiting ALVR client, either ALVR crashes and I can close it, or Quest tracking in the mobile dashboard is stuttering and I still have to restart the headset.

What are the optimal settings that will be “safer” for my headset, I have a dedicated (old ASUS N66U) access point directly next to me, to eliminate networking issues. 

H264 extends the time a bit I can play, but eventually that also dies...  is my headset broken? It does get quite hot when running ALVR.

Oh, I also chose NV12 setting in Video.

On a side note, I love ALVR and the quality and speed is definitely better than Oculus Link, which I can’t run this game PCARS2 without dialing everything down (seems GPU overhead is ridiculous on Link).

**Comment by MPfaffe** [comment]
Hi,

some recommendations:
make sure your quest is connected by 5 GHz wifi and it is the only connected device to 5 GHz wifi.
make sure that there are no/not many additional 5 GHz transmitters around (e.g. smartphones)
Routersettings: 
use seperated 5 Ghz wifi with 40 MHz bandwith (not combined with 2.4 Ghz), make network "not visible"
ALVR-Server Settings:
use default video buffer-calculation

hope it helps :-)

**Comment by walterklomp** [comment]
Yes I tried that. However I’m in an apartment block where everybody and their dog have a WiFi network... it seems ALVR can’t recover from too much interference. When it happens I also get a lot of fec errors. No packet loss by the way. Putting the AP less than a meter away doesn’t help.

**Comment by TNTRick** [comment]
hi, make sure you set your LAN speed lock to 1 Gigabite on PC.

**Comment by walterklomp** [comment]
I managed to get it stabilized now... put my best router close to where I sit, hide the SSID, find the most free control channel and now I can stream up to 100mbps... 150mbps also works but the lag becomes high...  thanks for the tips...
