### ISSUE TITLE
Help with deciphering frame timings.

### ISSUE THREAD

**Issue by TashaSkyUp** [JackD83/ALVR#109]
This is a representitive sample of my ALVR usage on a:
AMD 1700x
gtx970
16GB
windows 10
1GB network from inet to computer
5ghz hotspot from computer to quest
20mhz channel width.(only selections are 20 or AUTO)

I hoping for some guidance on what the problem is with the late start frames. 

GPU usage around 70%
Video gpu usage around 30%

![image](https://user-images.githubusercontent.com/15312630/73140047-8f096c00-4042-11ea-99b8-aad162331598.png)

**Comment by JackD83** [comment]
Your gtx970 can not keep up. With the Quest, your gpu has 13.8ms time to render a frame. Yours takes longer. Try to set the SteamVR super sampling to manual and 1.0 or lower. Lower the resolution of the game you are running, disable anti aliasing etc. You need an buffer of "idle" above your "Application" (blue) until it reaches 14ms
