### ISSUE TITLE
Re-Implement network

### ISSUE THREAD

**Issue by JackD83** [JackD83/ALVR#11]
ALVR is using a UDP socket to the HMD to stream data and transmit control messages. 
This should be split into one TCP connection for signaling and one for streaming

Currently, its possible that the network is loosing packages and the the messages to send I-Frames also gets also lost.

This would be a bigger change

**Comment by DavisNT** [comment]
I suggest using UDP rather than TCP, as UDP is better suited for realtime applications. 
In case of packetsloss TCP connection can stuck and it WILL re-transmit all the data. In case of video streaming, if some frames are lost there is no point in re-transmitting them - better to transmit current frame as IDR and resume normal transmission. 
I would also stick with UDP for control channel (to prevent it getting stuck on packetsloss).

**Comment by JackD83** [comment]
I'm with you on the video streaming, TCP would be a bad choice for that and with the currently implemented forward encoding, lost packages can be compensated. For the control of the video stream, a lot of signaling and re-sending is/has to be implemented to end up with the functions TCP is already providing.

I would split it like this:
SteamVR -> HMD
- Video  - UDP 
- Audio - UDP

HMD -> SteamVR
- Mic Audio - UDP
- Tracking - UDP
- Statistics - UDP
- IDR Request - TCP

And then the whole stream start/stop could be linked to the TCP socket:
- Server Socket on the HMD
- SteamVR (alvr_server) connects to HMD
- on established connection, streaming starts both ways
- on connection lost, streaming stops

**Comment by Entropy512** [comment]
For the IDR request, is it really necessary to have that be TCP as opposed to layering a very light stop-and-wait scheme over UDP for that particular message?

e.g. server will send an ACK when it receives an IDR request, if the client doesn't see an ACK within a certain period of time (or see evidence of an IDR), resend the IDR request?

**Comment by JackD83** [comment]
You are probably right. After the changes by @DavisNT  with the MIN_IDR_FRAME_INTERVAL, I had no problems what so ever with lost connections or bad image quality.

**Comment by zarik5** [comment]
Closed in favor of #242.
