### ISSUE TITLE
Superhot vr Hands not present

### ISSUE THREAD

**Issue by ScrambledGamingYT** [JackD83/ALVR#110]
Can anyone tell me if it is just me or does the hands in superhot vr not show up
Hoping to get a response thanks

**Comment by OlivierLDff** [comment]
I have the same problems and i already read an issue about this
- https://github.com/polygraphene/ALVR/issues/392

**Comment by JackD83** [comment]
Please go to properties and betas and select the "old-steamvr-patch" to play superhot vr. Works flawless including throwing stuff

**Comment by ScrambledGamingYT** [comment]
I am in the steam vr beta but I don't know how to choose an older patch as I can't find out how

**Comment by ScrambledGamingYT** [comment]
It is patch 1.0.8 right?

**Comment by JackD83** [comment]
yes, patch 1.0.8
