### ISSUE TITLE
Revive + ALVR + Robo Recall?

### ISSUE THREAD

**Issue by bad1dea** [JackD83/ALVR#112]
Anyone have this working?

When I try it, game opens (doesn't change from SteamVR Home)

Headset Error

You have a pending hardware issue that is preventing you from entering vr, please check that your headset and sensor are connected.

(Other apps, and games work from REVIVE Dashboard -- and my other STEAM VR games are working)

**Comment by bad1dea** [comment]
NM. Reboot fixed it all.

**Comment by SeriousOri** [comment]
> NM. hat exactly do you mean by NM.  Reboot fixed it all ??

> NM. Reboot fixed it all.

What exactly do you mean by NM. Reboot fixed it all ??
