### ISSUE TITLE
Using Vive Controllers with Quest results in offset in HMD position.

### ISSUE THREAD

**Issue by hvent90** [JackD83/ALVR#114]
Here is a photo showing how far the controllers become from the HMD. The controller's position seems to be correct, but the HMD has been offset once turning on the Vive controllers.
<img width="466" alt="Annotation 2020-02-03 142416" src="https://user-images.githubusercontent.com/5974764/73696313-e76aea00-4690-11ea-8845-7a03b3184abd.png">

Changing the offset applies it to both the HMD and controllers. I am looking to use the Vive Controllers to take advantage of my base stations for tracking :)

**Comment by JackD83** [comment]
I'm not sure how there could be an offset on the HMD. You need to calibrate your tracking space and align the coordinate systems of the quest and the vive tracker. That is not part of ALVR

**Comment by hvent90** [comment]
Thanks!
