### ISSUE TITLE
Add sharpen filter ?

### ISSUE THREAD

**Issue by nicoreda** [JackD83/ALVR#117]
Hello, I've made some tweak to the program to test some stuffs, despite I completly destroyed it (but it works lol) I managed to get a sharpen filter working, and it really help to sharp the image ! But I destroyed the saturation value because I don't know how to properly add one (I'll put it back later when I get the time) so saturation value replace sharpen value. You can try it, put saturation at 0.30 it would be enough. Also I don't know how to get width and height properly, you can see the hlsl file changed here https://github.com/nicoreda/ALVR/blob/experimental/alvr_server/shader/ColorCorrectionPixelShader.hlsl .
My question was, do you think you can implement something like this in the base ? It's something that bring the image really better imo
Sorry for my bad english ^^' have a good day :)
Demo pictures:
![image](https://user-images.githubusercontent.com/1252715/74054415-52dcf080-49de-11ea-80c9-12a126d8c68d.png)
![image](https://user-images.githubusercontent.com/1252715/74054437-5cfeef00-49de-11ea-8f65-1ae8cb04f80b.png)

**Comment by zarik5** [comment]
I'm the author of the original shader. Right now my schedule is full, but I can do this in 1-2 weeks. I'm also waiting on #118 to land because concurrent changes on WinForms (UI) are hardly mergeable.

**Comment by nicoreda** [comment]
Thanks for answering ! No problem and good luck ^^
