### ISSUE TITLE
Please provide PDB files for driver_alvr_server.dll

### ISSUE THREAD

**Issue by bjj** [JackD83/ALVR#124]
This will help Valve report bugs against ALVR which cause crashes in vrserver.exe. Currently (and for nearly a year) ALVR is responsible for the top 3 crash causes in vrserver.exe. We got the PDBs from the 2.4.0a5 release and reported detailed stacks, but there has been no further release in that series. It looks like this is the actively maintained branch, so if you can provide PDBs for the DLLs that people are actively using, we can report bugs here.

**Comment by JackD83** [comment]
I will provide the PDB for the next release. My guess is that most crashes are a result of incompatible Nvide GPUs.

**Comment by JackD83** [comment]
I released ev9 with the pdbs
