### ISSUE TITLE
Height adjustment

### ISSUE THREAD

**Issue by nk33** [JackD83/ALVR#128]
Hoping for help - can't figure out how to adjust the height on this version of ALVR - I am always a few metres below level...

**Comment by JackD83** [comment]
Please try the [Room-Setup](https://github.com/JackD83/ALVR/wiki/Room-Setup)

**Comment by nk33** [comment]
Hi mate – yes that’s what I did after a bit of searching….cheers mate!!

**Comment by nk33** [comment]
Hi mate,

Also, in Dirt 2, when i centre it i an sitting behind the front seat....so
I have to go back, set it then come forward again to be in the correct
place....is there a setting i can change in your alvr to correct this?

Thanks

Nick

**Comment by JackD83** [comment]
First, it’s not my alvr, many people contribute to this. Second is no, there is no such option. I have not tried Dirt 2 yet, but project cars 2 has a key to recenter you directly behind the wheel in any direction. I think you need something like this to be able to use wheel and paddles as input
