### ISSUE TITLE
alvr v4 with mic steaming latency problem 

### ISSUE THREAD

**Issue by jakefever191** [JackD83/ALVR#13]
i got alvr v4 but i have a big latency problem when mic steaming is off i get 70-80 ms  as normal as soon as i turn on the mic streaming it goes to 80000000 ms is this the software or my hardware i have a belkin ac1200 at 5ghz with a i5-3470 16gb of ddr3 1600 ram with a gtx 1050 ti lp

**Comment by jakefever191** [comment]
i overclocked the 1050 ti and it is now at 300ms so i guess its my gpu

**Comment by JackD83** [comment]
The problem is that your system is already at the lower end of VR capable hardware. You could try to lower the video resolution and/or the SteamVR supersampling. The upcoming fovead rendering could also improve your experience

**Comment by jakefever191** [comment]
the steamvr supersampling does not do anything when i play around with it tho

**Comment by jakefever191** [comment]
so u are adding  foveated rendering like in the oculus quest games how in the middle it is clear and around the sides it is lowered rendering

**Comment by jakefever191** [comment]
also wondering if you could make it so alvr goes in the windows taskbar so it can hide in there or something

**Comment by JackD83** [comment]
You have to enable custom resolution and then set the slider to something that works for you. You can try 20% to see if its working properly. 

Please make a new bug entry for the ui changes, makes it easier to track them.
