### ISSUE TITLE
Controller Latency 

### ISSUE THREAD

**Issue by Yuuki795** [JackD83/ALVR#131]
Back in the original version of ALVR the controllers jittered but had like no latency is there anyway to go back to that for beat saber?

**Comment by JackD83** [comment]
Got to the "other" tab in ALVR and set the controller pose offset to 0. Be aware that this will bring a lot of other problems like jitter and controller overshooting on fast movements

**Comment by Yuuki795** [comment]
I had this problem before in ALVR before but the jitter wont be a problem. Mind telling me what the default for rn is?

**Comment by JackD83** [comment]
The default pose offset is 0.01

**Comment by Yuuki795** [comment]
So I had set it to 0 it did nothing. You need to set it to -1 but i found setting it to -0.02 is a good setting so it doesn't jitter too much with not too much lag either.

**Comment by JackD83** [comment]
The value for a "good" setting depends pretty much on the person. For me, it was the 0.01. Glad you found yours

**Comment by tchesket** [comment]
Do you mind explaining exactly what controller pose offset means?

**Comment by jarrard** [comment]
-0.05 seems to have helped for my situation. And it was pretty bad for me. (Testing with TWD)
