### ISSUE TITLE
Oculus Error when running the client apg on Gear VR

### ISSUE THREAD

**Issue by thebender7** [JackD83/ALVR#132]
Hi!
After starting the app (ev9) and inserting the Galaxy Note 8 into the Gear VR Headset, I receive a message "Oculus update required. To learn how to update the Oculus app visit: support.oculus.com OK". I reinstalled the complete Oculus software and updated controller firmware but the error persistes. Any ideas? 
Thank You!

**Comment by JackD83** [comment]
This fork of alvr does only work on the Oculus Quest. Gear VR and Oculus Go are not supported

**Comment by thebender7** [comment]
Thanks, i was not aware of this. Does anybody know if there exists an active fork supporting the Gear VR as the original project is dead?

**Comment by JackD83** [comment]
You can check active forks using this link
https://github.com/polygraphene/ALVR/network

Unfortunately, there are no other active forks
