### ISSUE TITLE
Troubles loading drivers

### ISSUE THREAD

**Issue by thebender7** [JackD83/ALVR#133]
Hi!
I was trying to build and run the Desktop app in VS2019. All projects seem to build fine however when running I get an error message that the driver can not be found. I tried to copy the "driver" folder as well as the .dll files in  "libswresample" to the folder with the ALVR.exe as this corresponds to the file structure of the release version of the original ALVR. In this configuration the app starts, however it does not open SteamVR and does not find any devices.
Can someone please give me a hint on how to properly build and run the application from VS2019?

Thank You!

**Comment by JackD83** [comment]
You need the same structure as in the alvr releases (driver\bin\win64) starting with ALVR.exe
Just copy the release folder and replace ALVR.exe and driver_alvr_server.dll with the ones you build

The driver needs to be registered with SteamVR at the current location using the button in the "about" tab of alvr

**Comment by Zatratbat** [comment]
Sorry I'm new to this stuff, where's the release folder and what build stuff? sorry ik I sound stupid

**Comment by Zatratbat** [comment]
Also I'm having the same problem as this: https://github.com/polygraphene/ALVR/issues/603

**Comment by thebender7** [comment]
Are you trying to compile the source or just want to use the program? In latter case go to https://github.com/polygraphene/ALVR/releases/tag/v2.3.1 or, if you are using an Oculus Quest go to https://github.com/JackD83/ALVR/releases, download the (portable) zip and run alvr.exe

**Comment by JackD83** [comment]
@thebender7 this fork is not compatible with the original ALVR. Your links are misleading

The correct release page is 
https://github.com/JackD83/ALVR/releases

@Zatratbat if you are trying to build ALVR on your own and have never done developing before, I advised against it. 
ALVR is a very complex project with many dependencies to a multitude of different APIs. You should choose a simpler project to start your developer career.

If you problem is, that the alvr server is not launching, check the following: you need a 64bit CPU and a 64bit Windows, a Nvidia gpu with NVEnc or an And gpu with Amf support. You have to install the latest visual c++ runtime as stated on the release page.

If it's still not working, please make a new issue with your exact computer specs

**Comment by thebender7** [comment]
I am aware that it is not compatible and never stated that. The reason i was linking the original project was that Zatrabat posted his question there for the first time. I pointed him to this thread as i thought it might help him compiling. Sorry for the confusion.

**Comment by Dubstepas** [comment]
can u help me out, i cant run alvr and it says cannot load library. im running rx470 i3-9100f
