### ISSUE TITLE
Headset not detected in SteamVR when using Windows 10 Hotspot

### ISSUE THREAD

**Issue by TADDL01** [JackD83/ALVR#136]
I can connect the Quest with the server, but SteamVR shows the headset in standby.
Thats how it looks on the server:
![image](https://user-images.githubusercontent.com/36709449/76168283-a45bd500-616e-11ea-93f5-f1561ca2da89.png)
Reinstalled ALVR and SteamVR.
I have no problem when I connect to my  2.4 GHz router.
I was able to stream with the Vridge demo.

**Comment by JackD83** [comment]
That's a firewall issue. You need both udp ports 9943 and 9944 open to get ALVR working properly. I guess 9943 is still blocked in your case

**Comment by TADDL01** [comment]
There were already exceptions for ALVR and I added them for the ports, but it only works when I disable the firewall for public networks. I'm in a private network and windows says there is no public network active, I guess that a windows issue.
