### ISSUE TITLE
failed to start audio capture

### ISSUE THREAD

**Issue by ukalele94** [JackD83/ALVR#137]
I have recently downloaded the v9 version and this problem arised. sometimes it occured with v8 and caused steam to open in safe mode and gave this warning. Most other times it worked just fine. I attempted to change the audio settings as recommended in other issue threads but to no avail. No usb audio attached. Here is my crash log.
[ALVR_CrashLog_20200309_164612.log](https://github.com/JackD83/ALVR/files/4309570/ALVR_CrashLog_20200309_164612.log)

**Comment by JackD83** [comment]
It's a common problem with realtek audio devices. Please update to the latest drivers. Drivers from other vendors may be more up to date for your audio device. For example you have an Asus motherboard but the drivers for the same audio chip from msi are newer or you get the drivers directly from realtek.
Beside the driver, you need at least one working audio output that is not virtual. E.g the speakers of your monitors or headphones

**Comment by ukalele94** [comment]
I have attempted to update the drivers but the drivers seem to be all up to date. I will try to find any other possible drivers and report
