### ISSUE TITLE
Steamvr Pause Menu Does Not Work

### ISSUE THREAD

**Issue by CRKatri** [JackD83/ALVR#138]
Pressing the menu button on the left controller used to bring up the steamvr menu but now it brings it up but it's invisible, so you can't use it.

**Comment by JackD83** [comment]
I have seen this error with an earlier beta of steam VR.

If you are using a beta version, please revert to the regular version of steam VR. 

If you are not using the beta, please state the alvr version and your steam VR version. 
Try to uninstall and reinstall streamvr

**Comment by CRKatri** [comment]
I am using Steamvr version 1.10.22 and alvr version 2.4.0-experimental v9

**Comment by JackD83** [comment]
I just tested with ev9 and SteamVR 1.10.26 and the menu works just fine. 
Please try to reinstall steamvr

**Comment by CRKatri** [comment]
Alvr has stopped working for me entirely as of Steamvr version 1.10.28 because it is blocking the alvr extension, I am going to attempt downgrading it to 1.10.26

**Comment by CRKatri** [comment]
I was able to get alvr to work on 1.10.28 by opening C:\Program Files (x86)\Steam\config\steamvr.vrsettings in a text editor and set “Disabled By Safe Mode” to false on the alvr addon, however my menu is still not working

**Comment by JackD83** [comment]
I have tried all SteamVR versions from 1.10.28 and the betas up to 1.10.32. Steam menu is working all the time. Have you tried to completely uninstall and reinstall SteamVR?

**Comment by CRKatri** [comment]
I have tried multiple times to reinstall steamvr, the current version downloaded is 1.10.32
