### ISSUE TITLE
ALVR client and server on separate networks？

### ISSUE THREAD

**Issue by q1014723373** [JackD83/ALVR#139]
I ran NAT and turned off the firewall to find Oculus's IP address but the port was not 9944, and there was no screen when connected.，

I used the router's port forwarding function,
servers can find Clients under different networks,
But he is missing the port after connecting
The client and server are not under a NAT.
I do n’t want to play Oculus under a local area network.

**Comment by q1014723373** [comment]
![a](https://user-images.githubusercontent.com/26036741/76501425-3caece00-647d-11ea-89b2-cfa0811e04bd.PNG)

**Comment by q1014723373** [comment]
![b](https://user-images.githubusercontent.com/26036741/76501515-59e39c80-647d-11ea-8e97-ea503763f2f4.PNG)

**Comment by q1014723373** [comment]
![a](https://user-images.githubusercontent.com/26036741/76501541-6831b880-647d-11ea-8fc9-91d8e2d01aa6.PNG)

**Comment by q1014723373** [comment]
![b](https://user-images.githubusercontent.com/26036741/76502019-4127b680-647e-11ea-9778-3ef8ae715d53.jpg)

**Comment by q1014723373** [comment]
![MainTo](https://user-images.githubusercontent.com/26036741/76502214-9cf23f80-647e-11ea-8fe6-1a1ec2a7daa3.PNG)

**Comment by q1014723373** [comment]
![Connect123](https://user-images.githubusercontent.com/26036741/76502279-b8f5e100-647e-11ea-83b5-0509b01e7135.PNG)

**Comment by q1014723373** [comment]
I use the WiFi hotspot of 5g mobile network

**Comment by JackD83** [comment]
How do you use NAT? have you enabled some kind of port forwarding? You need port 9944 and 9945. 
The screenshot suggests that you are missing port 9945

**Comment by q1014723373** [comment]
> 您如何使用NAT？您启用了某种端口转发功能吗？您需要端口9944和9945。
> 该屏幕截图表明您缺少端口9945

I forwarded ports 9943 and 9944。

**Comment by q1014723373** [comment]
> 您如何使用NAT？您启用了某种端口转发功能吗？您需要端口9944和9945。
> 该屏幕截图表明您缺少端口9945

It can be used in some networks and the port is 9944, but most of the networks are not connected, and the port is always wrong

**Comment by q1014723373** [comment]
> 您如何使用NAT？您启用了某种端口转发功能吗？您需要端口9944和9945。
> 该屏幕截图表明您缺少端口9945

Sorry, my English is not very good

**Comment by q1014723373** [comment]
For example, he can connect under my friend's WiFi, but he can't connect with the 5g WiFi hotspot of my mobile phone

**Comment by JackD83** [comment]
Can you please describe your network? What is connected to what and where is ALVR running. Why do  you use NAT? And please update your posts and do not add new comments
