### ISSUE TITLE
Add message to set channel width to 40 MHz to prevent stuttering every few minutes

### ISSUE THREAD

**Issue by RobbeSchepens** [JackD83/ALVR#14]
If I may suggest adding a message in ALVR that recommends setting the 5 GHz channel width of your router or access point down from 80 to 40 MHz. 

I've been testing and searching for the weird artifact stuttering that happens every few minutes and this is what solves it. Multiple people have been reporting this issue on literally all streaming services: AMD Relive VR, VD, ALVR, VRidge. I think the best solution is to add a warning message in those services. The Oculus Quest's WiFi chip or driver is to blame for this. 

Please note that not all routers and access points allow you to adjust this setting. I had no luck adjusting this in my AVM FritzBox nor FritzRepeater. From googling, I think these router manufacturers allow adjusting this setting: Linksys, D Link, TP Link, MikroTik. Netgear and AVM FritzBox don't, as far as I can tell. I haven't searched for any others.

Edit: If anyone is looking for a good access point. I got the MikroTik wAP ac but it was difficult to set up and the connection was terrible. I sent it back and just got a TP Link RE650. Set up is easy and relatively quick. It is working really well. 5 GHz speed at 40 MHz is 400 Mbit (this might actually be the 40 MHz limit of the Quest's WiFi chip).

**Comment by JackD83** [comment]
Interesting find! Do you have any sources for that? I have a cheap router from my ISP and have already set my channel width to 20/40 mHz down from 20/40/80. I don't now why :)

I think there is also a connection between the used frequency and the throughput. Lower channels should be better, but I had to go up to 136 to find a free channel

**Comment by RobbeSchepens** [comment]
I tried a lot of things. At first I thought it was my GPU choking on VRAM. The GTX 970 is known to have a weaker controller for the last 0.5 GB of the 4 GB VRAM it has. So I tried my friend's 1080 Ti but the same issue appeared. I searched for others having this issue and it seemed to me it was pretty common. So I found a youtube video showing this issue quite clearly: 

https://youtu.be/PJAIMAt5IG0?t=255 "I get the occasional stream freeze where all I get is artifacts which takes like a second to recover. This could be my wifi connection. "

Many people believed it was their own wifi connection but since it seemed to happen to many people, I figured it must not be their own connection. I digged deeper and finally found this post: https://www.reddit.com/r/OculusQuest/comments/ckx0qx/this_is_how_to_remove_periodic_frame/ which refers to a Japanese article that found the solution to this problem first: https://otasyumi.site/vr/oculus-quest-steamvr-try-alvr-corresponding-to-the-latest-build-of-oculusquest

I had another guy test it and tested it myself, and yes indeed it did get rid of these stutters every few minutes.

**Comment by JackD83** [comment]
Any suggestion where I should put the message? Right now there is no info text or anything

**Comment by T3ER** [comment]
Interestingly enough this solved my connection issues with mic streaming where I would randomly lose connection. At times everything worked fine for long time.

**Comment by rgferreira** [comment]
Solved random issues here too. Thanks.

**Comment by Sztrovacsek81** [comment]
Thank you for this finding! This is my only problem with VR streaming I'll test it tonight.

**Comment by RobbeSchepens** [comment]
My first thought would be to put it in the Video tab as some people might be adjusting bitrate because of it, which frankly is not the real issue. Yet the Video tab is probably full. So I'm not sure.
