### ISSUE TITLE
Issue with error message from SteamVR. [Quest]

### ISSUE THREAD

**Issue by SuperSaiyanPig** [JackD83/ALVR#143]
When I boot up ALVR for my Quest, an error message pops up every time it tries to access SteamVR, preventing the headset from connecting visually to the SteamVR app entirely. "An error occurred while updating SteamVR (App currently running)". I have tried reinstalling SteamVR multiple times, tried seeing if any other steam client was running through task manager (no luck), tried reinstalling ALVR but I don't think thats where the problem lies. Every thing server wise is connecting fine: my headset, ALVR, and SteamVR. I'm lost.

**Comment by DavisNT** [comment]
Could it be this issue? 
https://github.com/JackD83/ALVR/issues/142 

That issue might also display the error message you described.

**Comment by DaGerber82** [comment]
having same issue

**Comment by ratozumbi** [comment]
what video card do you have?

**Comment by DaGerber82** [comment]
Sorry for the late reply!
I’m using what came with my hp gaming laptop-
Processor:AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx -
Display adapters-AMD Radeon(TM) RX Vega 10
/ NVIDIA GeForce GTX 1650-
