### ISSUE TITLE
Addons blocked on startup

### ISSUE THREAD

**Issue by simsetstreams** [JackD83/ALVR#144]
Whenever i start steamvr addons get blocked and the quest won't be detected, i used it for a while and it worked fine, alvr says that the server is down as well

**Comment by JackD83** [comment]
Seems to be an steam VR error. I tried beta 1.10.30 and it works again. 
1.10.28 even had a hotfix and is still broken

**Comment by CRKatri** [comment]
https://github.com/JackD83/ALVR/issues/138#issuecomment-599107017
