### ISSUE TITLE
Allow us to define a server ip on quest

### ISSUE THREAD

**Issue by KoromaruKoruko** [JackD83/ALVR#145]
i want to access ALVR over a SubRouter. But it doesn't find the server because of it having a different ip to the Client (IE Server 192.168.178.X Client 192.168.137.X), if there is a way around this without having to redo my entire house's network that would be grate.
but it would be better if we could tell the client to try and connect to a specific ip.

**Comment by DavisNT** [comment]
It is possible to have headset and ALVR server on separate subnets. Here is the relevant Wiki article: 
https://github.com/JackD83/ALVR/wiki/ALVR-client-and-server-on-separate-networks

**Comment by KoromaruKoruko** [comment]
I'd say that is more of a wook around, and that there should be a menu in the client to do this.

**Comment by JackD83** [comment]
Feel free to make a menu. The Client has currently no real UI, thats why its not so easy to just add an option

**Comment by KoromaruKoruko** [comment]
i'm afraid i don't know c/c++ too well, i'm a c# programmer. so i don't think it would be something i can do. unless its OK to move the ALVR Client over to having a partial back end.

**Comment by DavisNT** [comment]
AFAIK creating a GUI on headset for the setting is not an easy task (AFAIK Oculus Quest specific APIs must be used for that). 
Users who install ALVR on their headsets from PC already have proper adb setup and should be able to adjust the configuration quite easily.

**Comment by JackD83** [comment]
@KoromaruKoruko the ALVR gui is c#. We could do a client settigs panel that requires the quest to be conencted via usb cable and update setting that way like sideqest is doing. This could also allow the gui to install or update the client on the quest

**Comment by KoromaruKoruko** [comment]
@JackD83 that sounds like the best case, much easier then implementing a client side UI Framework, while also being extremely user friendly.

Whenever i have time ill get to adding it in myself.
