### ISSUE TITLE
Crash in Cleanup

### ISSUE THREAD

**Issue by bjj** [JackD83/ALVR#147]
Looks like 0.9 (with PDB) has not rolled out much yet, but if I compare the polygraphene version to this one, I suspect the crash is still in:

```
void ClientConnection::Stop()
{
	Log(L"Listener::Stop().");
	m_bExiting = true;
	m_Socket->Shutdown();
	m_ControlSocket->Shutdown();
	Join();
}
```

I'm guessing there are cases where m_Socket is null.

**Comment by JackD83** [comment]
Are you sure about m_Socket being null? In my understanding, this can only be if the the socket was not initialized at all. 
I will add a check

**Comment by bjj** [comment]
No, not sure. It's crashing in the Stop function and m_ControlSocket looks like it can't be null, so I was assuming it had to be m_Socket somehow.

It's possible this bug only exists on the polygraphene version, but there must be many installs of it out there still.

**Comment by JackD83** [comment]
Fix released with ev10
