### ISSUE TITLE
#request to add steam-vr tracking prediction and oculus quest link logo and icons for steam-vr 

### ISSUE THREAD

**Issue by jakefever191** [JackD83/ALVR#150]
hey, I was wondering if u are going to add SteamVR tracking prediction when Quest is used with SteamVR. also would u be able to change the icons to be the same as the oculus link 

![download](https://user-images.githubusercontent.com/44185776/77259619-8aca9980-6ce7-11ea-9b47-059f4515ece3.jpg)

**Comment by JackD83** [comment]
SteamVR tracking prediction is already used. That's what the pose offset parameter in the other tab is for. I can set the correct icons for the quest if you tell me how

**Comment by jakefever191** [comment]
was wondering the icons for it lay somewhere in the code

**Comment by jakefever191** [comment]
![image](https://user-images.githubusercontent.com/44185776/77519184-f1b4a200-6ee3-11ea-933e-c6a2c446f1af.png)
is this where the icons go? sorry code is not my strong point
