### ISSUE TITLE
HKEY_CLASSES_ROOT_\vrmonitor\shell\Open\command is not found

### ISSUE THREAD

**Issue by jeangariepy** [JackD83/ALVR#153]
Hello,

When i start de ALVR programm, i have a ALVR Fatal Error message.

---No SteamVR installation. Please check installation of SteamVR
HKEY_CLASSES_ROOT_\vrmonitor\shell\Open\command is not found

My Steam is install. When i am start Google Earth VR, i have this message : OpenVR failed to initialize with the given error : VRInitErroe_Init_pathRegistryNotFound.

Thank's

**Comment by bjj** [comment]
It's telling you to install [SteamVR](https://store.steampowered.com/app/250820/SteamVR/) which is available for free on Steam.

**Comment by jeangariepy** [comment]
Thank's. It's work.
Now some bug with ALVR.
