### ISSUE TITLE
It would be nice if alvr_server used vr::VRDriverLog()

### ISSUE THREAD

**Issue by bjj** [JackD83/ALVR#154]
At initialization:

```
	VR_INIT_WATCHDOG_DRIVER_CONTEXT( pDriverContext );
	// pass vr::VRDriverLog() to some part of your logging system
```

Once the driver context is captured, vr::VRDriverLog() can be used to log information back to the merged vrserver.txt log. This is useful if users report errors with a system report, or if errors reported to Valve need to be passed along to ALVR.

Totally fine to log *both* to your own logs and to `vr::VRDriverLog()->Log(...)`

**Comment by JackD83** [comment]
I tried to log everything from ALVR to the driver log, but its too much and SteamVR starts freezing. 
I should check all usages of the logger and only the relevant data should be logged to SteamVR

**Comment by JackD83** [comment]
Implemented with ev10
