### ISSUE TITLE
Expose JSON GUI-driver communication protocol to the user

### ISSUE THREAD

**Issue by zarik5** [JackD83/ALVR#155]
Make the GUI save the json (read by the driver) to file system instead of to a memory mapped file. This is intended to be used for easier debugging and to allow anyone interested to tinker with settings not available in the GUI (for example the strings that define the Rift S or Vive headset) without recompiling ALVR. The GUI elements should then sync to this file instead of their user.config file.

**Comment by clach04** [comment]
@zarik5 any more thoughts on this? I saw https://github.com/JackD83/ALVR/issues/183 and I like you idea of moving config out to json (even a file on the filesystem) so alternative tools can be used to change config.

I saw that a web interface was suggested which seems a good way for both the quest and PC (or even phone) to change things, https://github.com/jsonform/jsonform could be a good way to get a relatively cheap UI up and running.

If you get config file support working, please ping me and I can look at throwing together a config only prototype for server/client.

**Comment by zarik5** [comment]
I already implemented the GUI-server communication through json. It's still not fully tested but I will get to that in the next weeks. Join the new official ALVR discord server for announcements: https://discord.gg/KbKk3UM

**Comment by clach04** [comment]
Great! 👍 

I may have been looking in the wrong place in Discord but I did find the https://github.com/JackD83/ALVR/tree/web-ui branch. I'm guessing this is in progress and needs a build system to work on it.

**Comment by zarik5** [comment]
The new discord doensn't cite the web-ui branch because everything is still broken and unfinished.
I will close this issue once the web-ui branch has been merged.
