### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by FansZou** [JackD83/ALVR#159]
After 15 minutes of alvr running at 72 frames, the performance of alvr will decrease gradually from 72 frames until it is completely stuck. I notice that this problem has existed from previous versions. Is it possible to solve it?

**Comment by FansZou** [comment]
When the performance of the client has been reduced, the client will be stuck directly when the server is shut down and re opened

**Comment by JackD83** [comment]
Duplicate issue #70
