### ISSUE TITLE
Controllers latency

### ISSUE THREAD

**Issue by rgferreira** [JackD83/ALVR#16]
Hey, I just tried today the brand new experimental v5 and I'm having around 100ms latency just on the controllers. Everything else is OK, and some returning sound from my Quest microphone as well.

**Comment by veryjos** [comment]
I get this too. I think it's from some of the controller smoothing that JackD83 was playing around with. The older version definitely had less latency, although more jittery.

**Comment by JackD83** [comment]
Controller tracking will always be difficult. There are so many factors that influence the latency and the motion prediction. Its not something like "100ms" constantly, but depends on your movements and even the movement of the headset.

There are many parameters that influence the movement that can be changed:

- Tracking is currently async to the rendering and running at 3*72=216Hz
- movement prediction is set to 0 to get the latest tracking info -> no prediction on the quest
- info is send to SteamVR
- tracking info is fed into SteamVR with an offset of 10ms to enable SteamVR pose prediction
- the tracking point on the Quest is different that the point on the Rift S. Angular acceleration and linear acceleration of the controller needed to be transformed to the new reference.

There is a trade off between fast but wobbly and overshooting controllers and controllers that have a certain latency. For me, the current settings are perfectly playable for games like Skyrim, Fallout or Arizona Sunshine. Games like Beat Saber might be an issue. 

You can change the 10ms offset for SteamVR in the "Other" tab of ALVR (Controller Pose Offset). 
The parameter defines how old the data that is fed into SteamVR is and controls the SteamVR pose prediction. Set it to 0 to disable all predictions

**Comment by veryjos** [comment]
Ah I see! Yes, setting that value lower (to a negative number like -0.2) feels much like the older builds and is perfect for me. It's definitely extrapolating to reduce perceived latency with a negative number.

What's the purpose of delaying/interpolating by 100ms by default?

**Comment by JackD83** [comment]
The default is 0.01=10ms. Its the amount of time I needed to be able swing my sword in skyrim without feeling weird. Its very possible that this value depends on the person, thats why its on the gui and you can change it on the fly

**Comment by rgferreira** [comment]
Thank you guys, now I kind of understand the "pose offset" parameter. Indeed, lowering the value solved the issue. I had a value of 2 there, and it made the tracking soooo smooth but extremely laggy, which now understand perfectly why. Now, with a value of 0 I'm playing shooters very nicely and I will try small positive values as @JackD83 suggested. Thank you very much.
