### ISSUE TITLE
V8/V9 server not connecting (staying connected)

### ISSUE THREAD

**Issue by KomputerWhiz** [JackD83/ALVR#162]
after connecting through alvr, when i start server, steam vr launches then crashes a few moments afterwards, this problem was present at the release of v8 and has continued onto v9, though both of these versions do not work, v7 has still worked flawlessly, currently it displays the hmd on the most recent steam vr 1.10.32, but no controllers. ive had no luck with either #90 nor #142 issue fixes. ive tried deleting local appdata , and also have the latest vc++ along with attempting a few other quick fixes

**Comment by lyndonguitar** [comment]
your issue sounds VERY similar to my issue, fortunately I pinpointed the cause. This might be your case as well. See #160  

That might be the fix, although if you are using that feature in particular, you will have to wait for a fix.

**Comment by KomputerWhiz** [comment]
no luck im afraid, just tried it and it still crashed

**Comment by KomputerWhiz** [comment]
i believe i have narrowed the problem down to the keplar mobile series graphics cards being no longer supported for graphics driver updates after 425.31. should v8/v9 rely on the newer drivers it could very well be possible this is the issue. though i am still uncertain the newer alvr versions rely on the new drivers in shape or form
