### ISSUE TITLE
Controller not working in specific games with ALVR & Quest

### ISSUE THREAD

**Issue by MeisterHeinz** [JackD83/ALVR#163]
Hi there
first thank you for this fork, working nice with my Quest and games like Skyrim VR or Red Matter.
Today I tried out A-Tech Cybernetics but unfortunately I am not able to move in this game, it seems that ALVR is messing it up with the controller type. 
I am using the Quest Touch controllers but in the VR view inside the game I've got virtual Vive controllers in my hands. The motion is tracked perfect but the two sticks are not working.
When playing with the Oculus link cable, its working perfect. Can this be fixed by myself?

**Comment by ratozumbi** [comment]
Did you tried to fix buttons binding using steam panel?
https://www.windowscentral.com/how-create-custom-keybindings-steamvr

If you do create a binding that works, please share it with the community :)

**Comment by MeisterHeinz** [comment]
> First:
> Are you using Rift S controllers on ALVR? (check that on ALVR "other" tab -> headset emulation mode)

In the "Other" tab there is "Oculus Rift S" selected.

> Second:
> Did you tried to fix buttons binding using steam panel?
> https://www.windowscentral.com/how-create-custom-keybindings-steamvr
> 
> If you do create a binding that works, please share it with the community :)

I tried adding the joystick function to the sticks but that did not help. :-(


> Final note:
> It is possible that the developers of the game don't support Rift S controllers. I had this same problem with the game Bounce, which did not support WMR controllers. I had to contact the game devs and ask for support

Well, as I wrote when using the Oculus Link via USB-C-cable it is working fine. So it seems to be something related to ALVR.
