### ISSUE TITLE
[Oculus Quest] Headset not found V9 

### ISSUE THREAD

**Issue by DewenX7** [JackD83/ALVR#165]
So from yestarday until now i can't manage to make ALVR find my quest, i tried a bunch o things that are write here but nothing works for me, or maybe i was doing them wrong, so i need a little help please.

**Comment by ratozumbi** [comment]
Please confirm if:
- You have executed add_firewall_rules.bat as administrator
- ALVR server (PC) and client (quest) are on the same network

**Comment by Ranatos** [comment]
I have almost the same problem. ALVR can´t reconnect/find my Quest, after i disconnect it from ALVR. I have to restart my PC and only after that, ALVR detects my headset. Closing ALVR and Steam doesn´t help, but a restart does. Maybe there is something running in the backround, preventing ALVR to find devices.
