### ISSUE TITLE
Half Life: Alyx finger movement on controllers are not working

### ISSUE THREAD

**Issue by ScrambledGamingYT** [JackD83/ALVR#167]
when I push the trigger, grip, or rest my hand on 1 of the thumb sensors it doesn't do the hand gestures like in Boneworks and I've seen that this works with oculus link but there is no problem grabbing things in game. This is not a major game breaking issue I just wanted to know if it is something to do with ALVR

**Comment by zarik5** [comment]
This has already been fixed on master branch but it is not on any release yet.

@JackD83 I'm not working on ALVR now, you can make a new release whenever you want.
I think you should make a faster release schedule; the best solution would be to make a beta/pre-release for each new feature/fix, then when gathered enough feedback, make a stable release.

**Comment by JackD83** [comment]
@zarik5 I'm currently working on some other improvements, but there will be a release the next few days
