### ISSUE TITLE
Vr tracking prediction

### ISSUE THREAD

**Issue by Schwiftywaffles** [JackD83/ALVR#169]
### Bug reports:

Not really a bug so I don't know if I should post it here but...
The way Virtual Desktop improves tracking is by predicting where your hands are going and moving them to that location.
I think you should do something like that because it greatly improves tracking and that combined with ALVR's smoothness would make it so much better than virtual desktop

**Comment by Hubbit200** [comment]
If something like that would be possible without being too difficult, to reduce apparent delay by even just a few milliseconds, that would be amazing!

**Comment by JackD83** [comment]
ALVR is already using the SteamVR tracking prediction. Use the "Pose time offset" in the other tab to adjust the time to your liking. 0.01 is the time I personally chose. Its a balance between responsiveness and overshooting in fast movements. I believe VR is using 0.

This does not affect the overall delay, its just a prediction. An improvement could be made by implementing a sliced rendering with multiple encoders like the Link or VD do. This is a big change and no one has time to do it

**Comment by veryjos** [comment]
Jack, can you elaborate on encoders? Do you mean utilizing both a CPU-based encoder and a GPU-based encoder in parallel?

**Comment by JackD83** [comment]
I mean multiple instances of the encoder to encode slices of the images while other slices are transferred  in parallel like the Link is doing it

[Oculus](https://developer.oculus.com/blog/how-does-oculus-link-work-the-architecture-pipeline-and-aadt-explained/)

**Comment by veryjos** [comment]
Ah, I thought ALVR already supported sliced encoding, but I think I mistook sliced foveation mode for sliced encoding. Thanks for clarifying :)
