### ISSUE TITLE
Suggestion: Option for resetting mic device instance id 

### ISSUE THREAD

**Issue by T3ER** [JackD83/ALVR#17]
I had an issue after disconnecting devices from my pc while it was off, replugging everything and starting pc where the virtual cable used for mic streaming didn't receive sound anymore. I dug into the issue by looking into the virtual cable in device manager. I found out that the device instance id was different to the one I found in alvr config file. I then pasted the id from device manager to the config and mic streaming worked again although the id had changed once again after I closed alvr. The mic streaming worked even after it had changed by itself. This could explain why the mic streaming didnt work on the very first time I tried it until I reinstalled a bunch of other virtual adapters I had. There has also always been something about the device and many others I have "not migrated due to partial or ambiguous match." I've searched for solution to that problem before but it can't always be fixed. Cable output has been the default mic in windows settings the whole.

**Comment by JackD83** [comment]
What device instance do you mean? The CABLE input is queried every start of the alvr_server and has no config. It is Identified by the name starting with "CABLE" and stored anywhere

**Comment by T3ER** [comment]
...Appdata/Local/ALVR/... has user.config. The windows device manager calls the id how I previously mentioned it. I right click on the virtual cable in device manager, properties and the tab with list of events on the device. If the id is not even stored in any config I am really confused on how changing the sound device id I mistakenly thought was mic device fixed the issue.

**Comment by JackD83** [comment]
The audio device stored in the user config is the device that is captured and send to the HMD. If you somehow have the CABLE Input (a playback device) as the default or if you selected CABLE Input manually in the ALVR ui, you created a loop which stops the mic from working. 

This would all be much easier with a dedicated mic from ALVR, but it requires to write a windows driver and I never done something like that nor do I have the time to read into it
