### ISSUE TITLE
ALVR Fatal Error

### ISSUE THREAD

**Issue by JT-cyber** [JackD83/ALVR#170]
v2.4.0-experimental v10

On launching ALVR with admin privileges, I get the error message below:  
![image](https://user-images.githubusercontent.com/63797045/79465236-f7893900-7ff2-11ea-8235-947987ef73c6.png)

And this is from Regedit:  
![image](https://user-images.githubusercontent.com/63797045/79465261-01ab3780-7ff3-11ea-85be-45f8992f95a1.png)

If I launch it without admin privileges, then it launches and appears to be working, but the Quest doesn't detect the server.  

Can you help or advise?  Thanks

**Comment by JT-cyber** [comment]
Made some progress, but still problems.  Oculus updated its OS today, and seems to connect to ALVR OK.  But still a problem either with Steamvr or the way ALVR connects to or launches Steamvr.  

After pressing 'Start server', I get two error messages from ALVR, then Steamvr opens also with an error message.  

![image](https://user-images.githubusercontent.com/63797045/79563663-1d6f1600-80a5-11ea-8a92-339194247610.png)

Once again, any help would be much appreciated, thanks

**Comment by jakefever191** [comment]
Is steam on your c: drive because I Don't think alvr can find steam if it's not on your c drive I had that problem with a friend and it was fix after we put steam and steamvr on his c drive

**Comment by JT-cyber** [comment]
I have checked my c drive and it is in there and it still doesn’t work

Thank you very much if you have any more advice let me know

**Comment by JackD83** [comment]
Don't run alvr as admin

> If I launch it without admin privileges, then it launches and appears to be working, but the Quest doesn't detect the server.

Then there is something else going on with your system. Firewall ports are open?
