### ISSUE TITLE
Quest mic very quiet in Pavlov and other games

### ISSUE THREAD

**Issue by jakefever191** [JackD83/ALVR#173]
So my mic works fine in vrchat but games like Pavlov vr I'm all most dead silent same with echo vr the mic is loud when I test then in discord and other apps idk if this is the game or steamvr or alvr could someone shed some light

**Comment by walterklomp** [comment]
I hear nothing. There is no error but I can’t get anything to work on the mic, neither on STEAMVR or Pavlov

**Comment by ratozumbi** [comment]
This looks like the kind of problem that can be solved by only changing the input device within the game sounds option. Have you tried that?

**Comment by jakefever191** [comment]
I don't have a different mic to uses

**Comment by ratozumbi** [comment]
does the game understands that there is a microphone connected?

**Comment by jakefever191** [comment]
the mic is working but it's very very quiet Pavlov does not let u change the mic levels same with echo vr

**Comment by walterklomp** [comment]
I have the same problem... set it to virtual cable but I hear nothing and no green bars in windows either.  I can remember it ever working though... reinstalled everything, made sure I allow to give access to mic on quest... nothing....

**Comment by walterklomp** [comment]
Is there any way we can actually test if there is data coming from the quest mic?

**Comment by jakefever191** [comment]
O no myic works with alvr it's just depending on the game it can be very quiet
