### ISSUE TITLE
AMD VCE 2 compatible scaling

### ISSUE THREAD

**Issue by Guthenberg** [JackD83/ALVR#175]
### Bug reports:

AMD up to VCE 2 only supports encoding of 1920px wide content. With the Quest reolution of 2880 this is a scaling of 2/3.

When selecting a scaling of 75% the resolution is to high for the AMD VCE 2 encoder, but 50% is not using the full available resolution.

#### Environment

GPU: AMD R9 290
ALVR: ev10

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

I will add a pull request for 66% scaling, but the correct 66.6666666666666% cannot be entered since it is a array of integers.

**Comment by JackD83** [comment]
I have no AMD  card to verify your pull requests. Can someone please test?

**Comment by astronaut701** [comment]
I'll try to build and test this pull request, I am running on an AMD RX580.

**Comment by JackD83** [comment]
Building should be very easy. You need Visual Studio 19 with .Net and  C++ and cuda 10.1.
After that, just build every part (shared, CUDA,AMF) and then alvr_server. The ALVR part will build the .net gui

I will make a test build if I have the time

**Comment by astronaut701** [comment]
I'll give it another shot. It builds successfully (I think?) but the question now how do I run it?

**Comment by astronaut701** [comment]
Any updates guys? I know it's a been a while since, but I think the VCE 2 compatibility should be put in if the UI can be fixed to allow for that extra percentage in the drop-down menu.

**Comment by zarik5** [comment]
A new ALVR version is in the making. You will be able to do this using the new advanced settings.

**Comment by astronaut701** [comment]
Alright then! In that case, this issue should probably be closed since the new version is currently being worked on and will include the compatibility in the new release. (This should also be closed to reduce clutter..) Thanks for the heads up Zarik!

**Comment by zarik5** [comment]
The new release will not be out in at least a month, but you can follow the developement in the "web-ui" branch.
