### ISSUE TITLE
Weak, sometimes no vibration oculus quest

### ISSUE THREAD

**Issue by TheWors3** [JackD83/ALVR#180]
I'm using the latest ALVR v10, my pc is a ryzen 2700x, 1080ti and 16gb ram. Basically when using alvr the vibration inside steamvr games is weak, and sometimes nothing happens when vibration should ocurr... Tested pistol whip, beat saber and hl alyx, vibration works fine and better in virtual desktop and link. latency and performance is fine, the only problem being the haptics.

**Comment by loui013** [comment]
I can confirm this is the case. An easy way toreproduce this is in your Steam home environment: Push up on your joystick to activate the teleport circle, then hover over the edge of the blue floor area (move the circle outside of the valid teleportation area and back in). For me haptic feedback usually only occurs after the third time and when it does, it is very weak.

**Comment by JackD83** [comment]
Duplicate issue with #21 

Code for the haptic feedback can be found in the [ALVRClient](https://github.com/JackD83/ALVRClient/blob/experimental/app/src/main/cpp/ovr_context.cpp)

Pull requests are always welcome!
