### ISSUE TITLE
Quest: ALVR and SteamVR keep interrupting height weirdly.

### ISSUE THREAD

**Issue by jarrard** [JackD83/ALVR#181]
I have this odd issue with this software atm which I never experienced with Link or VirtualDesktop where SteamVR requires stationary height re-configuration often. 

If I set the headset on the floor this is fine but if I put the headset on and recenter it assumes I'm on the floor again. IF I then set the headset to my approx height and try resetting procedure (hold right menu button down) it ends up not configuring the height right, sometimes I'm too high, sometimes not high enough, other times my angular motion is skewed..

ALVR needs some work where it just injects this data from the Quest directly into SteamVR like how Virtual Desktop does (which requires no extra SteamVR tweaking to work).

Currently using ALVR on Windows10 with experimental version 10 on PC and Quest.

**Comment by jarrard** [comment]
I'll mess with it some more, see what I can figure out.

**Comment by ratozumbi** [comment]
As a workaround for the time, try this program.
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings

Its a dashboard menu for Steam VR. There you will find a button "fix floor height"

**Comment by jarrard** [comment]
Its a intermittent issue which you seem to be able to work around or only crops up now and again.  I was able to work around it after resetting the setup a couple times.
