### ISSUE TITLE
Could not run ev10

### ISSUE THREAD

**Issue by skyuanev** [JackD83/ALVR#189]
#### Bug reports:

The new ev10 edition could not run anymore on my computer. 

It throws an exception :"get sound device failed system runtime.interopServices.SEHException" at front and stuck in loading. 

The environment had no problem with previous releases, so it might be caused by something changed in the new release.

**Comment by MPfaffe** [comment]
have you tried to set within ALVR server the audio device to your dedicated soundcard/-device (e.g. "realtek xyz", "xfi" )?

maybe it helps...

in my case the "standard setting" jumps everytime to the "oculus virtual audio". In this case I don't get any sound, but for me there is no failure notification... if i set it to my realtek onboard sound manually within ALVR server everything is fine.

**Comment by skyuanev** [comment]
I wanted to set the audio device but I couldn't even get into the program because of the exception..

**Comment by skyuanev** [comment]
And it is weird that, this version would not create a config file in %LOCALAPPDATA%\ALVR

**Comment by MPfaffe** [comment]
have you deleted this folder (%LOCALAPPDATA%\ALVR) before installing the new alvr server?

**Comment by JackD83** [comment]
Du you have sound devices with non latin characters (like Chinese? ) If yes, its a bug in ev10 and will be fixed in the next release. https://github.com/JackD83/ALVR/pull/185

**Comment by skyuanev** [comment]
Maybe this is the case. I will wait to test the next release then. Apperaciate your hard working on ALVR👍
