### ISSUE TITLE
Request : Get back to disable controller option please.

### ISSUE THREAD

**Issue by ShawnMayer** [JackD83/ALVR#19]
Hello JackD83!

Thanks to your great jobs.

I have a request.

I have been using ALVR with index controller and some trackers. In Alvr alpha 5, I can disable couclus controller, but Now I can't. So I have to remove battery every time for using ALVR.

Can you add option for disable controller?

Thank you in advanced.

**Comment by JackD83** [comment]
The option was removed during the refactoring of the controller input to directly use SteamVR without the FreePie lib.  I'm not sure if I should support this use case, but pull requests are always welcome.

Out of curiosity: How did you get the controllers working along side ALVR anyway? I did not know that two drivers can run at the same time. What about the calibration quest<->index controller?

**Comment by ShawnMayer** [comment]
Hello JackD83,

You can use 2 VR system, changing steamvr setting file to activeMultipleDrivers=true in C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings\default

and calibrate by OpenVR SpaceCalibarate.

**Comment by JackD83** [comment]
Oh wow, that’s some process to get them working. Personally I don’t like the controller that much. 
I will see what I can do about the quest controllers, should be a small change. I’m currently a little busy at work, but I will come back to it

**Comment by hvent90** [comment]
@ShawnMayer I get a weird HMD offset when using Vive controllers. Do you get this? If so, how did you fix it? #114
