### ISSUE TITLE
V10 in WIN10 ERROR~

### ISSUE THREAD

**Issue by foreversos** [JackD83/ALVR#192]
![QQ截图20200510195510](https://user-images.githubusercontent.com/3012313/81498592-6ad35180-92f8-11ea-82f9-4888cd3a36bd.png)
![QQ截图20200510195521](https://user-images.githubusercontent.com/3012313/81498595-6c047e80-92f8-11ea-90e7-dc41bcbf0371.png)

**Comment by MPfaffe** [comment]
see 
https://github.com/JackD83/ALVR/issues/189

**Comment by foreversos** [comment]
OK.wait new version realse
