### ISSUE TITLE
ALVR isnt working (i didnt understand #23)

### ISSUE THREAD

**Issue by mymousebroke** [JackD83/ALVR#195]
![alvrcrash](https://user-images.githubusercontent.com/47399587/81731076-750e6080-945c-11ea-8a76-ac9d2c48ec89.png)

**Comment by MPfaffe** [comment]
is the latest vc runtime installed?
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by mymousebroke** [comment]
sorry for being late but my C; drive has a x86 file soi assume so

**Comment by JackD83** [comment]
Please install SteamVR though steam. If you already have, try installing it to the C drive
