### ISSUE TITLE
Oculus Quest isn't detected by SteamVR when using Windows Mobile Hotspot

### ISSUE THREAD

**Issue by Arenovas** [JackD83/ALVR#196]
# Please follow the general troubleshooting steps first:

- [X ] I ran "add_firewall_rules.bat" as administrator and checked that the ports are open in the firewall
- [X ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

The Oculus Quest doesn't get detected by Steam when connecting it through a Windows Mobile Hotspot despite ALVR detecting and connecting to the headset just fine. SteamVR detects the headset just fine though when connected through a non hotspot connection.

#### Environment

What hardware do you have: Pentium G4560, GTX 1050
What version of ALVR and SteamVR have you tried. 
Experimental v10 and SteamVR 1.11.11
Do you have the latest Windows updates?
Windows 10 1909

Not sure if anything else is needed, but I'd be happy to supply any more info if necessary.

**Comment by Nightlychaos** [comment]
Why would you use a mobile hotspot? Also those specs are not that well suited for vr in general

**Comment by Arenovas** [comment]
Using the mobile Hotspot should get me a much more stable connection than my current setup since currently my PC is using WiFi and I can't connect it via ethernet. 
And I'm well aware that my PC is below spec for VR but I've gotten a few games working well enough on it with the Quest.

**Comment by orangpelupa** [comment]
it works fine for me, at least when i was using ALVR.... version 7 or 8 i think. have not tried on v10.

btw try pinging your quest thru CMD. 

start, cmd
ping oculusquestipaddress

**Comment by Arenovas** [comment]
Huh, might give those earlier versions a test in a few days. And would pinging it really give any other results? Cause it shows up just fine on the ALVR program under a different IP than it does when connected to the normal router. It just doesn't get picked up by SteamVR.

**Comment by orangpelupa** [comment]
yeah pingin will make sure you got a connection to it and its not a bug with incorrect ip address being connected.

btw if using older alvr, make sure to uninstall and install the alvr driver from the right most tab (i think it  was "About"?) just to be extra safe.

**Comment by Arenovas** [comment]
I pinged the Quest and it successfully pinged back. And I also tried using v8 and v7 of ALVR but those didn't work either. I also briefly tried Vridge's trial with the mobile hotspot and that had no problems interacting with SteamVR, so I wonder what's going on with ALVR and the hotspot.

**Comment by JackD83** [comment]
This is most likely a firewall issue. VRidge and VD use a different network architecture. 

For ALVR, the headset sends packages freely to the pc and the firewall has to allow that. Pinging the headset is the wrong way.

Try to temporarily disable the firewall and try again

**Comment by Arenovas** [comment]
Alright, so disabling my firewall did allow me to finally connect my headset using the mobile hotspot. Although now I wonder if there's anyway to do so without having to disable the entire firewall.
