### ISSUE TITLE
Positive Feedback

### ISSUE THREAD

**Issue by ocquesttest** [JackD83/ALVR#2]
Hey JackD83,

i just want to give you some positive Feedback.
Im playing SteamVR games via ALVR (original) for a couple of weeks now.
Today i tested your ALVR experimental 3 and it works really well!
With the fixed default resoultion and the seperated render resolution from video resolution the output on the quest seems to be much sharper than in the original ALVR and games run very smooth and well for me.
Also the controller fixes are nice too, however there is a bit of a delay in tilting them but i guess it will get better with every new release..  :D

Some short questions:
Would you recommend using "Suppress Frame Drop" and/or "Force 60Hz"?
And what is "Disable send throttling" for?

Thanks for this fork and keep up the great work!
(Win10 Pro 1809 64bit, Nvidia GTX 1070, Driver 430.64)

**Comment by gunnarweibrink** [comment]
+1

Using your "experimentals" after seeing that there is no progress in polygraphenes work.
With your intense work it is getting better and better!
- Tracking is getting much more precize (and annoying bugs with it are gone)
- v3 should remove any display issues witch mainly rely on recognizing the quest as a go
(before, the sharpness of identical apps differ between quest nantive and ALVR/SteamVR)

Is there a way to support you in your really great work?
Many thanks!

best regards,
Gunnar

**Comment by JackD83** [comment]
I'm lucky that my work is already supported by my employer, so nothing else is needed. 
Pull requests are always welcome :)

I would not recommend the 60Hz mode. I re-enabled the function in the latest build, but it makes me sick very fast. I would rather reduce the video resolution that the fps.

"Suppress Frame Drop" and "Disable send throttling" are options that influence how packets are send to the HMD. I have not looked into it on how useful they are.
