### ISSUE TITLE
mic keeps playing back to the quest back

### ISSUE THREAD

**Issue by jakefever191** [JackD83/ALVR#20]
how do i stop from hearing my mic in vr???

**Comment by JackD83** [comment]
make sure you **don't** select the "CABLE Input" device as your default windows playback device nor as audio device in the ALVR ui

**Comment by jakefever191** [comment]
when i do that it says steamvr has failed

**Comment by JackD83** [comment]
Do you have other audio playback devices?  I think you need at least one.

**Comment by jakefever191** [comment]
i do now no matter what play back i pick as mic steaming is on it won't run

**Comment by jakefever191** [comment]
it only works if i do cable-input

**Comment by JackD83** [comment]
Please make a screenshot of your Windows audio settings and the Sound settings of ALVR. 
You can drag&drop the screenshots directly in the comments field here on github

**Comment by jakefever191** [comment]
![Captureththth](https://user-images.githubusercontent.com/44185776/64323290-524bc280-d018-11e9-878d-d8c188057688.PNG)

**Comment by JackD83** [comment]
Hmm, that looks like its supposed to. Could you try the first speakers you have as default device? 
Is your default device a USB headset?

You can also enable debug logging by creating a "logs" folder inside the alvr folder and activating the checkbox in the alvr ui. Requires a restart of SteamVr

**Comment by jakefever191** [comment]
it did this and there was no log 
![Capture](https://user-images.githubusercontent.com/44185776/64324473-963fc700-d01a-11e9-9963-3b027167afae.PNG)
![Captureththth](https://user-images.githubusercontent.com/44185776/64324474-96d85d80-d01a-11e9-9ec6-dbbb542edad8.PNG)

**Comment by jakefever191** [comment]
and it went from start steam vr to push connect on alvr

**Comment by jakefever191** [comment]
@JackD83

**Comment by jakefever191** [comment]
could it be the drivers

**Comment by jakefever191** [comment]
y am i the only one with this problem

**Comment by JackD83** [comment]
It seems that way. Does the streaming work if you just uncheck the mic checkbox? You opened another issue?! 

And please stop spamming the issue with one liners!

**Comment by jakefever191** [comment]
the steaming does work if i uncheck the mic checkbox

**Comment by jakefever191** [comment]
is there a different way fpr mic steaming ik it's unlikely

**Comment by jakefever191** [comment]
hey i got it working then came back a few hour ago and the mic kind of workinh but the CABLE-input (playback)is the mic and idk how to fix it

**Comment by jakefever191** [comment]
the mic is working now but it's showing up as CABLE-input under playback but CABLE-output has nothing coming through and that's under recording

**Comment by jakefever191** [comment]
i fixed it

**Comment by JackD83** [comment]
Nice! Could you please tell us how you fixed it? Maybe someone will encounter the same problem

**Comment by jakefever191** [comment]
it was working but as soon as a restarted my the mic stop working it show up under play back and won't pick up under record

**Comment by jakefever191** [comment]
my fix is i have to reinstall the drivers every time i restart my pc
