### ISSUE TITLE
Found wrong version client

### ISSUE THREAD

**Issue by hyudryu** [JackD83/ALVR#200]
# Please follow the general troubleshooting steps first:

- [X] I ran "add_firewall_rules.bat" as adimistrator and checked that the ports are open in the firewall
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

Server is not establishing a connection with the client: "Found wrong version client. Check for client/server update.

Both the Windows server and APK were downloaded from the same repository, drivers have been installed.

#### Environment

What hardware do you have: **Oculus Quest, Windows 10, GTX1060**
What version of ALVR and SteamVR have you tried: **V10 experimental**
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number: **Version 1903 OS Build 18362.836**

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by JackD83** [comment]
You probably had an old version on the quest and installing the new version failed. Please uninstall ALVR completely from the quest and then re-install the latest version
