### ISSUE TITLE
Quest disconnects 2-5 seconds after I enter SteamVR

### ISSUE THREAD

**Issue by drtart** [JackD83/ALVR#203]
# Please follow the general troubleshooting steps first:

- [x] I ran "add_firewall_rules.bat" as adimistrator and checked that the ports are open in the firewall
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Everything looks good and connects, but 2-5 seconds after I connect the quest headset disconnects but I can hear the controllers still sending an input (press B and steamvr makes a noise)

I've tried several versions of ALVR and all have same result. Tried 5 different network configurations as well. All ports forwarded. 

I think the update to 17 maybe to blame?
#### Environement

What hardware do you have: 9750h, 1660ti, Audio
What version of ALVR and SteamVR have you tried. v10, v9, v5, v3
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number - yes

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by MPfaffe** [comment]
did you deactivate the "smartconnect" (maybe other name) function in your router? 
otherwise it will switch between 5G and 2.4G Wifi with short disconnects... make sure the quest is connected all the time to 5G WIFI (recommendation: 80 MHz bandwith)
