### ISSUE TITLE
Severe audio delay

### ISSUE THREAD

**Issue by dmeff** [JackD83/ALVR#206]
Audio arrives to the headset with a LOT of delay. I can tell because if I leave the PC speakers on they sound like maybe half a second or a second before the headset speakers.

Is it something with my setup or is it a bug?

CPU: i5 4590
GPU GTX 1070
Mother: Asustek H97M
RAM: 12GB

I'm using the latest versin of this ALVR and latest version of SteamVR

**Comment by MPfaffe** [comment]
yes, half a second sounds very much... but is the audio synchron to the videooutput in the quest?

**Comment by dmeff** [comment]
Ok, even though I'm absolutely certain that I hadn't touched anything other than the "Stream Quest Microphone" setting, I reset settings to default and it improved massively (even after re-enabling the stream quest microphone setting)

If it gets out of sync again I'll update this, but for now it seems something had gotten misconfigured somehow

**Comment by dmeff** [comment]
Nevermind, the delay is back and reverting settings again isn't fixing it so that might just been a coincidence.

I'm connected through a 5ghz router AC set on 40hz and like 1m away from me, so I don't think connection is the issue.  The ALVR server reports:

60ms total latency
6ms Encode Latency
12ms Transport latency
8ms Decode latency

**Comment by MPfaffe** [comment]
"the video is synched" 
you mean quest-video and quest-audio are synched? than the audio delay should be just the "60ms total latency" (delay between PC and Quest output) in my opinion. I can imagine that the simultan audio playback of PC and Quest sounds weird ;-)

Since an quest firmware update (I think in January) i would recommend to use a 80 MHz channel bandwith.

**Comment by dmeff** [comment]
No, I mean that there is no delay in the video feed. So if I click a button I see it instantly but hear the click about half a second later.

I'll try the 80hz option

**Comment by dmeff** [comment]
This is still happening. I haven't managed to fix it

**Comment by theFrenchDutch** [comment]
Can others confirm that this is how it is for everone with audio streaming (half to full second lag ?) As I have had the same since using ALVR, my only issue with it !

**Comment by electronstudio** [comment]
I don't notice any lag. (Maybe 100ms, but certainly not 500ms).  @dmeff 's PC specs are pretty low, probably the bare minimum needed to run SteamVR (and then there's the extra encoding overhead imposed by ALVR) so maybe that could be an issue?

**Comment by dmeff** [comment]
The cpu could be a bottleneck, but I only see it running at around 80% when playing. I don't think that's the problem

**Comment by theFrenchDutch** [comment]
That might be the issue, my PC is a quite old i5 4570 paired with a 1060. Will check that out :)

**Comment by Sztrovacsek81** [comment]
No, with the I7 cpu there is a latency in ALVR but no latency in Virtual Desktop.
I think the audio streaming is not quite as good implemented as in VD.
