### ISSUE TITLE
Strange Hand Tracking Brokenness

### ISSUE THREAD

**Issue by Hayden-da-Serg** [JackD83/ALVR#207]
So I was going to go try out the hand tracking but I noticed a very strange issue with the hand posing, the following screenshots were taken in NeosVR however this can be replicated in SteamVR Home by using the Hand models

![unknown](https://user-images.githubusercontent.com/25524760/83255141-1e4b9b00-a16d-11ea-87ec-ca2f8390dbb6.png)

![unknown1](https://user-images.githubusercontent.com/25524760/83255124-17bd2380-a16d-11ea-8f75-767ecfbfd002.png)

I have my hand splayed out in front of me with the back of my palm facing towards me, I'm not sure what values their offset by, but they definitely aren't right.

I'm using SteamVR Beta 1.12.5 and ALVR Experimental V10 on Windows 10 Home.
My ALVR is set to emulate the Rift S and Hand Tracking mode is set to Oculus Rift S no pinch, everything else is pretty much set to default.

**Comment by zarik5** [comment]
For now you can try fix this using "Left position offset" in Other tab.

**Comment by Hayden-da-Serg** [comment]
Thanks! Yes, this did fix the rotation issue, however, the position doesn't seem to match up with what I'm seeing in SteamVR, I might just have to play with the settings a bit to get it to align properly, but I think this is good enough to mark as closed.
