### ISSUE TITLE
Oculus update required

### ISSUE THREAD

**Issue by MollerAndre** [JackD83/ALVR#213]
Can not be used on my Gear VR device (Galaxy S7) because ALVR requires an Oculus update but my Oculus app is already the latest. Other injected apps work fine.

**Comment by Ekristoffe** [comment]
What kind of error do you have ?

**Comment by MollerAndre** [comment]
I installed APK using Injector for GearVR just like I always do with other homebrew VR apps. Since custom apps do not appear in Oculus library I start it from apps then, when requested, I insert it inside Gear VR visor and it says that Oculus needs to be updated (then exits and normal Oculus Home appears)... but Oculus already is the latest version available for Gear VR (9.0.0.182.473) which is different from the one available for Oculus devices and no longer supported by Samsung (as far as I know) so there won't be any updates in the future but that was not a problem with many other existing Oculus apps. I suppose this fork of ALVR requires a newer version of Oculus that is not (and never will) available for Gear VR devices.

**Comment by JackD83** [comment]
This fork is for the Oculus Quest only and does not support the GearVR or the Oculus Go. To my knowledge, there are no updated versions for that devices
