### ISSUE TITLE
suggestion post APKs in release downloads seperately

### ISSUE THREAD

**Issue by clach04** [JackD83/ALVR#215]
### Features:

It would be faster for me if I could download APK releases from https://github.com/JackD83/ALVR/releases on my Quest directly.

Right now the process I use is; download the zip, extract the APK, upload to an ftp server, then from Quest ftp/http it down in the Browser and install via Cx FileExplorer https://play.google.com/store/apps/details?id=com.cxinventor.file.explorer

this would make it a little bit easier (at least for me personally ;)) to update the headset (I try to avoid plugging it in to the PC as my PC is not near my play space).

**Comment by zarik5** [comment]
The release will be available on Sidequest once it hits stable. Anyway @JackD83, as @clach04 said, it would be better to have the client and server as separate files.

**Comment by zarik5** [comment]
I could make the release myself but I prefer to leave this to Jack because he is the one that has access to the sidequest page.

**Comment by JackD83** [comment]
I used the all-in-one zip for the pre-releases to avoid any confusion which apk belongs to what server. The final release will be separated as all previous releases and be on sidequest as well.
