### ISSUE TITLE
Height fix / Apply Offeset is missing from the settings

### ISSUE THREAD

**Issue by sitte** [JackD83/ALVR#22]
I'm testing from yesterday. I have to admit it works better than original ALVR. Big congrats.

There is one thing that is missing from original ALVR and that is fix for players height. It was in Other>Apply Offeset in original ALVR.  I'm plaing sitting low on couh so Oculus Quest is detecting that I'm just above the ground. In Steam VR home I'm a head laying on the ground or even below it. Can You consider adding this functionality back?

**Comment by JackD83** [comment]
Actually, no, You have to calibrate your room in SteamVR correctly:

- start the streaming with ALVR
- start the room setup
- put the headset on the ground and calibrate a "standing" room with the headset on height 0
- You might need to prevent the Quest from going into sleep mode by covering up the sensor between the lenses

Now the floor in the Oculus and the floor of SteamVR match. You can press and hold the oculus button on the right controller to recenter the space at your current position!

If you still want to adjust your playspace, use [Advanced Settings](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings) inside of SteamVR

**Comment by sitte** [comment]
Thank You. It works.

**Comment by rgreer4** [comment]
A side note -- if you've done the full Steam setup at least once, and the floor wanders off later (like after updating ALVR), in the mentioned Advanced Settings you can pick "Fix Floor" and just put a controller on the floor, and it'll reset it super easy.
