### ISSUE TITLE
[minor] Incomplete error message

### ISSUE THREAD

**Issue by ratozumbi** [JackD83/ALVR#220]
[This ](https://github.com/polygraphene/ALVR/issues/506)error message is not showing up in version 2.4.0-experimental v11

It's only shown partially as "Failed to initialize CEncoder. A"

**Comment by zarik5** [comment]
This is a known problem caused by invalid wide UTF-16 strings to UTF-8 strings conversion. The fix would be to find every use of wide strings and change it to UTF-8 everywhere. You can try this yourself if you can/have time.

**Comment by zarik5** [comment]
I should have fixed this. It will be in the next release.
