### ISSUE TITLE
Get Error Message: "Could not create graphics device for adapter 0. Requires a minimum of two graphics cards." when trying to start SteamVR

### ISSUE THREAD

**Issue by smpurkis** [JackD83/ALVR#222]
### Bug reports:

When I try to start SteamVR this message pops up and nothing else happens. The graphics card is minimum for SteamVR, so not sure why it isn't working.
Could not create graphics device for adapter 0. Requires a minimum of two graphics cards.

#### Environement

What hardware do you have: 
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, Quadcore, 
Dual GPUs: GeForce GTX 1050 Ti 4GB, Intel(R) HD Graphics 630,
Realtek High Definition Audio
Latest ALVR (Experimental v11, 2.4.0), Latest SteamVR (1.12.5)
Windows 10, Version 1903, Build 18362.900

**Comment by JackD83** [comment]
Is your primary monitor plugged into the Intel or nvidia card? Has to be the Geforce to work properly

**Comment by MPfaffe** [comment]
@smpurkis 
please try the advices from
https://github.com/JackD83/ALVR/issues/188

it should be a similiar issue, but in my opinion the compatibility advices (use x.264, 60 Hz, 50% resolution) can be ignored in your case as the 1050TI should be able to use standard ALVR settings.

please give feedback, if you can solve the issue or there are still problems. Thank you in advance!

**Comment by smpurkis** [comment]
@JackD83 @MPfaffe Thank you both! Worked perfectly. 
Switched the preferred graphics card in NVIDIA Control Panel and worked a treat.
