### ISSUE TITLE
Blinking between SteamVR and ALVR Menu

### ISSUE THREAD

**Issue by faw312** [JackD83/ALVR#229]
I have a problem with my alvr server/client
I have GTX 1650(laptop) and intel i7-9750H
The problem is that when im in **steamvr** on the headset, for 5-10 secs evrything is working alright but after that it *blinks* to the **alvr** menu and after a few secs it goes back to **steamvr** and it loops like that.

**Comment by zarik5** [comment]
Try again with the latest v12 beta
