### ISSUE TITLE
Controller flashing in game (Oculus Go)

### ISSUE THREAD

**Issue by IntelligentCappy** [JackD83/ALVR#232]
I've just upgraded from polygraphene's version to this one, and my controller is flashing rapidly, and sometimes it's not even visible. Controls appear to work fine, though. It seems to be accurately tracked.

## Specs

AMD Ryzen 5 3600
NVIDIA GeForce GTX 1060 (REPLACING SOON)
Latest SteamVR and ALVR Experimental V11
Running Windows 10 Version 2004, build 19041.388

**Comment by zarik5** [comment]
This fork does not officially support the Oculus Go, you need polygraphene's version.
