### ISSUE TITLE
Setup of v12.0.0-beta1 fails

### ISSUE THREAD

**Issue by Silent-Hunter** [JackD83/ALVR#233]
- [N] I ran "add_firewall_rules.bat" as adimistrator and checked that the ports are open in the firewall: I did not do this as the file is missing in this version.
- [Y] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

Clicking "Add firewall rules" causes ALVR server to give error code -1

Clicking next and clicking to install the driver causes a window with the title "ALVR crashed" to popup. Inside the window, it says "The system cannot find the file specified. (os error 2)".

I did run ALVR server as admin.

#### Environement

What hardware do you have: CPU, GPU, Audio: AMD Ryzen 5 3600, AMD Radeon 580, Generic USB sound card
What version of ALVR and SteamVR have you tried: ALVR server v12.0.0-beta.1 and SteamVR 1.13.10
Do you have the latest Windows updates?: Windows version is 2004 (OS Build 19041.388)

**Comment by Silent-Hunter** [comment]
Apparently it matters what folder you run it from. I was running it from the downloads folder where I unpacked it. I put it in my user folder, and it works fine.

**Comment by zarik5** [comment]
-1 error on firewall rules means failed to get admin privileges. This is maybe because you were already running with admin privileges. The error when registering the driver is because you have a non standard location for the steamvr installation.

**Comment by zarik5** [comment]
I verified that it does not matter where you extract ALVR server. The firewall rules fail is because either you didn't install SteamVR or you didn't launch it one time (before launching ALVR), so it didn't do it's first time setup.

**Comment by Silent-Hunter** [comment]
Weird, SteamVR was installed and being used prior to this. I was using it with Virtual Desktop Streamer.
