### ISSUE TITLE
v12 Beta -- Manual Client not connecting

### ISSUE THREAD

**Issue by Tilade** [JackD83/ALVR#235]
# Please follow the general troubleshooting steps first:

- [X ] I ran "add_firewall_rules.bat" as administrator and checked that the ports are open in the firewall
- [X ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

Setting the IP address of a manual client does not connect to the client. A Wireshark capture makes mention to the IP address and port correctly for port 9944. There is no communication on port 9943 (If I understand correctly, this is because that's used for the media flow and the hello packet hasn't been received on 9944).   The firewall includes proper rules for 9944 and 9943 (as it was working on v10 and v11).

#### Environement

What hardware do you have:  Using an AWS G4 GPU Instance with security group rules allowing all internal and external traffic
What version of ALVR and SteamVR have you tried? :  Worked perfectly under ALVR v10 & 11 (using ADB to manually set the server to connect to IP). Tried v12 Beta and not connecting.

Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number:  Windows Server 2012 R2

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by Tilade** [comment]
Update -- once I manually added the IP to the client like for V11 using ADB, it connected. But the Quest client still displays "Select Trust on the Server". I can't find a way to actually launch a session/game now that it's connected.

**Comment by maxer456** [comment]
Required firewall exceptions are different between v11 and v12.
For v12, you need to allow traffic for alvr_web_server.exe (not ALVR.exe) on ports 9943 and 8082, the latter is needed for dashboard access, though the in-VR dashboard probably won't work on that setup right now. Warnings on the [wiki](https://github.com/JackD83/ALVR/wiki/ALVR-client-and-server-on-separate-networks) still apply.

**Comment by Tilade** [comment]
> Required firewall exceptions are different between v11 and v12.
> For v12, you need to allow traffic for alvr_web_server.exe (not ALVR.exe) on ports 9943 and 8082, the latter is needed for dashboard access, though the in-VR dashboard probably won't work on that setup right now. Warnings on the [wiki](https://github.com/JackD83/ALVR/wiki/ALVR-client-and-server-on-separate-networks) still apply.

I'm not seeing any traffic on 9943 and 8082 after filtering in wireshark. I see a ton on 9944 and 9943 after it connects though.  I also can confirm the application firewall in windows is applied to alvr_web_server.exe.  Still no luck

**Comment by maxer456** [comment]
> I see a ton on 9944 and 9943 after it connects though.

What do you mean by 'after it connects'? Is the "click on Trust" message in the headset smooth or lagging when you're turning your head?

On port 9943 you should see a message from the Quest, then a response from the server. Can you open the dashboard at http://\<server ip\>:8082/ in the Quest web browser (or on another PC connected to the AWS instance)?

**Comment by Tilade** [comment]
I ended up disabling the windows firewall and port 8082 connected over the headset browser. But still doesn't show connection unless I force setting the server IP using ADB connected to the Quest (QQ: is this still necessary?).  Once I do that, I still see the same "click on trust" message within the headset as if it isn't connected. Motion is smooth.  But on the server monitor, it shows traffic and Wireshark displays traffic on both 9944 and 9943.  Attached is what the server displays after entering the server IP within ADB,  The headset still says "Click Trust" as if it isn't connected.
![image](https://user-images.githubusercontent.com/22228458/88433859-e9567000-cdcc-11ea-95c4-e32fb09d1c67.png)

**Comment by maxer456** [comment]
Yes, you still need to set a target server using ADB.
From the smooth motion, is seems the client isn't receiving a response from the server even though the server receives a connection, sends a response, starts SteamVR and starts streaming.

If you can see outgoing traffic on port 9943, that's the server responding to a connection request. You can check if it does respond and if nothing is blocking the response (though I doubt anything is blocking it, considering v11 worked for you).

**Comment by zarik5** [comment]
@Tilade Sorry, the manual client feature was half backed and must be removed for v12. It will be implemented properly in ALVR v13.
