### ISSUE TITLE
Stutter whenever i turn my head

### ISSUE THREAD

**Issue by NitroxPower** [JackD83/ALVR#236]
I am using ALVR v11 with latest windows 10 updates and latest SteamVR. My computer has: i7-2600K, RTX2060, 8 GB DDR3 Ram, Wifi Router 2.4 Ghz (Wired ethernet connection from pc to router, wireless from router to headset). 

My issue is that there is a noticable amount of stutter when using it. I have tried to lower bitrate and increase buffer but no difference. So i am not that sure whats causing that. The video Quality and latency are really great. The only issue is that there some stutter or glitching whenever i turn with my headset. When standing still and just move my controllers and such it doesn't happen only when i move with my headset. Anything that i can do to get rid of that other than getting a 5 GHz network since not available here? Latency and etc are fine its just that. If it requires more detail about my issue i can record and make a video to show exactly what i mean.

**Comment by Tilade** [comment]
This isn't really an issue--this is a problem with poor wifi. You're using 2.4ghz which is extremely limiting. You should use 5Gz wifi at all times. Doesn't matter if it's hardwired--it's the weakest link (like adding larger pipes to plumbing don't matter if you reduce it higher in the chain).

**Comment by NitroxPower** [comment]
Yeah but like are we sure that thats the issue? Because its not that it constantly happens. Whatever i don't have money to spare for 5 Ghz Router. Woop
