### ISSUE TITLE
SteamVR Does Not Detect Quest Headset Over ALVR

### ISSUE THREAD

**Issue by TylerAdamsUNCO** [JackD83/ALVR#237]
# Please follow the general troubleshooting steps first:

- [N ] I ran "add_firewall_rules.bat" as adimistrator and checked that the ports are open in the firewall
- It doesn't exist on Version 12.0, but I did add the firewall rules from within the client and checked that the exceptions were in the firewall, as can be seen here:
![Capture](https://user-images.githubusercontent.com/32653655/88449051-0f960300-ce01-11ea-8e59-ceeb4e9480dc.PNG)

- [Y ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Oculus Quest headset properly connects and shows up in ALVR, but when SteamVR launches it cannot detect headset.
![Capture](https://user-images.githubusercontent.com/32653655/88447672-174eab00-cdf3-11ea-82db-513c8af55ff0.PNG)

 Additionally, session log has many of these error messages inside.
21:08:49.821687800 [INFO] Failed to send log with websocket: IO error: An established connection was aborted by the software in your host machine. (os error 10053)

This occurs after adding firewall rules and registering ALVR drivers.

#### Environment

What hardware do you have: CPU, GPU, Audio
CPU: Intel I5-9600K
GPU: Nvidia Geforce GTX 980
Audio: Default Intel?
What version of ALVR and SteamVR have you tried. 
ALVR: Version 12.0.0 beta-1
Steam VR: Version 1.13.10
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number: Version 2004

**Comment by maxer456** [comment]
From what SteamVR says, it looks like it's not loading the ALVR driver.
Try the "Unregister all drivers" option in ALVR's Installation tab, then register ALVR driver again. If that doesn't help, please post vrserver.txt (SteamVR vrserver's log, you can find it where you installed Steam, in Steam\logs) after you close SteamVR.

**Comment by TylerAdamsUNCO** [comment]
[vrserver.txt](https://github.com/JackD83/ALVR/files/4975954/vrserver.txt)
Here's the vrserver log. Unregistering and then registering the ALVR drivers did not work unfortunately.

**Comment by TylerAdamsUNCO** [comment]
I was missing the Visual C++ 2019 Redistributable Package found here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
