### ISSUE TITLE
v12 and Win7 support

### ISSUE THREAD

**Issue by DocMAX** [JackD83/ALVR#238]
ALVR v12 now crashes on Win7 (works with v11) with error "Failed to initialize CEncoder".
Can you please maintain Win7 support in v12?

**Comment by zarik5** [comment]
ALVR v12 dropped support for Windows 7 as part of a cleanup of the codebase. The support could return in a future update but it has a very low priority.

**Comment by DocMAX** [comment]
OK, thanks.
