### ISSUE TITLE
This variant on SideQuest?

### ISSUE THREAD

**Issue by phyxfire** [JackD83/ALVR#24]
Any chance that this fork can be put up as a unique ALVR variant on SideQuest? Especially since the original now seems to be abandonware

**Comment by JackD83** [comment]
I’m not using SideQuest. If you want it includes, please ask them.

**Comment by JackD83** [comment]
Ownership of the ALVR app on SideQuest was transferred to me and I updated the page with the latest ev9 release. 

https://sidequestvr.com/#/app/9
