### ISSUE TITLE
On boxVR I experience vibration lag after some time

### ISSUE THREAD

**Issue by MonsieurKas** [JackD83/ALVR#240]
On BoxVr, with v12 Beta 2 and 3 I experience controller lag after 5 minutes. And after 10 minutes I experience major video distortion.
The first 5 minutes everything seems fine.

Don't have this issue with v12 beta1

**Comment by MPfaffe** [comment]
did you increase the buffer setting?

stay on default settings ;-)

refer to https://github.com/JackD83/ALVR/issues/70

**Comment by MonsieurKas** [comment]
I left it on default from the wizard. It's weird because as you progress in the game controller vibrator is lagging up and after 10 min. gameplay everything starting to get laggy.

Not having this on beta1 from v12.

Is there something I can give you to help, like logs or something?

**Comment by MonsieurKas** [comment]
Found the issue, my bad.
I forgot I changed the latency setting in game. I put it on 70 then completely forgot about about that.
It works better on 25ms.
