### ISSUE TITLE
Switch from Warp to Rocket

### ISSUE THREAD

**Issue by zarik5** [JackD83/ALVR#272]
Switch from Warp to Rocket as the web server library for the following reasons:
* Warp lengthens the compilation times due to heavy use of generics.
* The heavy overloaded use of filter functions makes the code difficult to write/modify if you're not familiar with the API.
* Rocket has recently became compilable on stable Rust.
* Rocket denies REST tree traversal by default.

Rocket doesn't support async yet, maybe it's better to wait.

**Comment by maxer456** [comment]
All of the points are covered by the recent move to from warp to hyper, so I think it's fine to close this.
