### ISSUE TITLE
Sharpen Filter broken

### ISSUE THREAD

**Issue by nicoreda** [JackD83/ALVR#274]
Hello, the sharpen filter seem to use the one before v11, got some weird black line on some edges of a gradient which isn't the case in v11.
![com polygraphene alvr-20200804-144034](https://user-images.githubusercontent.com/1252715/89294975-9009fe80-d660-11ea-8b26-119ce4186acb.jpg)

**Comment by zarik5** [comment]
This could be caused by the new default value for the gamma. @ohtaketakeshi did fix this for the experimental brach (v11) but was not ported to web-ui (v12).

**Comment by maxer456** [comment]
The mentioned fix is now used again as of v13.0.0.
