### ISSUE TITLE
Controllers problem

### ISSUE THREAD

**Issue by beyhes** [JackD83/ALVR#28]
Hi, I ve been using Jacks version since first release.
I had no problem with v4 version. 
Just updated steamvr and also v5. Now controllers are vive pro looks and menu button keeps on clicking automatically...  so basically I can not do anything :(

**Comment by JackD83** [comment]
Try to reinstall everything from scratch:

Execute driver_uninstall.bat in the driver folder
Delete the install folder (ALVR does not use the registry)
If you already deleted the folder without executing driver_uninstall.bat:
Open C:\Users\%USERNAME%\AppData\Local\openvr\openvrpaths.vrpath and check install directory
Execute "C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrpathreg.exe" removedriver (install folder) in Command Prompt

Delete C:\Users\%USERNAME%\AppData\Local\ALVR 

Uninstall alvr from your quest with `adb uninstall com.polygraphene.alvr`

**Comment by JackD83** [comment]
closed due to inactivity
