### ISSUE TITLE
Setup Github Actions for release

### ISSUE THREAD

**Issue by zarik5** [JackD83/ALVR#282]
The action should bump version of only server, only client or both. It should build (using `cargo xtask publish`) and attach binaries to the release.

**Comment by zarik5** [comment]
@maxer456 Could you maybe try this?

**Comment by maxer456** [comment]
Sure. Manual selection of which version to bump?

**Comment by zarik5** [comment]
Thank you. Ideally it would be better to allow specifying the version manually.
