### ISSUE TITLE
Experimental v5 crashes, ev4 works

### ISSUE THREAD

**Issue by DavisNT** [JackD83/ALVR#29]
Experimental v5 (ALVR server binaries from GitHub release and ALVRClient built from https://github.com/JackD83/ALVRClient/commit/dbaaf13393f161882ddb771ddc37f9b55dabb1d0 or https://github.com/JackD83/ALVRClient/commit/7a20a4e3f435967793ca562d8f4162bae47fdeb1 + https://github.com/JackD83/ALVRClient/pull/1) is constantly crashing when starting Steam. 

Experimental v3 (ALVR server binaries from GitHub release and ALVRClient built from source with the same modification) is working.
All ALVR settings (`%LOCALAPPDATA%\ALVR` folder) on PC were deleted. FFR was not enabled.

Excerpt from the crashlog: 

    Exception: Unhandled Exception.
    ExceptionCode=E06D7363
    Address=000007FEFD2AB87D (000007FEE4DF0000 + 00000000184BB87D)
    OSVer: MajorVersion=6 MinorVersion=1 Build=7601
    Module: 000007FEE4DF0000
    ----------------------------------------
    [00:20:18.089 698] got tracking info 3582 -0.313637 -0.078612 -0.065789 0.943994
    [00:20:18.089 698] CONTROLLER 0 0.000000,0.000000,0.000000 - 0.000734,-0.004234,0.005565
    [00:20:18.089 698] Controller0 0 1: 00000000 00000013 0.000000:0.000000
    [00:20:18.089 698] CONTROLLER 1 0.000000,0.000000,0.000000 - -0.000308,0.000604,0.002268
    [00:20:18.089 698] Controller1 1 2: 00000000 00000011 0.000000:0.000000
    [00:20:18.089 698] Rotation Matrix=(0.978984, 0.173519, -0.107151, 0.000000) (-0.074897, 0.794608, 0.602485, 0.000000) (0.189685, -0.581798, 0.790905, 0.000000)
    [00:20:18.089 698] GetPose: Rotation=(-0.313637, -0.078612, -0.065789, 0.943994) Position=(0.010037, -0.055899, -0.135191)
    [00:20:18.089 698] Try to send.
    [00:20:18.089 698] Poller::Do(). Select 10000 us
    [00:20:18.089 698] Cuda kernel execution failed. code=18 invalid texture reference
    [00:20:18.089 698] Unhandled Exception.
    ExceptionCode=E06D7363
    Address=000007FEFD2AB87D (000007FEE4DF0000 + 00000000184BB87D)
    [00:20:18.089 698] GetNextSwapTextureSetIndex 0000000040001280 0000000040001340 0 0
    ========== Exception info start ==========
    ExceptionCode=E06D7363 Address=000007FEFD2AB87D ThreadId=7388
    RaiseException(RaiseException) +61
    ========== Exception info end ==========

Has anybody else faced similar issue?

**Comment by JackD83** [comment]
A very strange error.
What hardware setup do you have? You already wrote me that you updated to the latest nvidia driver. I have two working setups with two different quests, but both have a GTX1070 and the latest 436.15 driver.

Have you tried to uninstall the alvr_driver and re-install? Maybe something is stuck.

Maybe @zarik5 has more insight, the changes from ev4  to 5 came from him.

**Comment by DavisNT** [comment]
I have Nvidia GTX 1660 Ti. Driver version is 436.15. 
I have tried to click "Uninstall driver" and "Install driver". 
Just tested and ALVR Experimental v4 is working (together with ALVRClient ev3). So the problem is introduced in ev5. 
CC: @zarik5

**Comment by JackD83** [comment]
I just upgraded from Visual Studio 17 to 19 and from CUDA 9.2 to 10.1
Maybe you give it a try. You need to rebuild everything and reinstall the alvr driver

**Comment by KitsuneShan** [comment]
I can confirm that it crashes for me too. What crashes is SteamVR and then I get an error message which I assume it's from SteamVR too? Or maybe ALVR but the application keeps it open and "working" (not hang). V4 works perfectly fine and it's the one that I am using right now. I have tried several times going back and forth with V5 and there is no way of making it to work. I always uninstall and reinstall drivers. There is something on that build that makes it to not work. I don't even enabled FFR. So, unless there is some charasteristic introduced that requires Win10 (I use Win7 right now) I have no idea what could it be. Either way, if for some reason the addition of FFR would require such feature, it would be better if we could still use the software turning it off otherwise people like me wouldn't be able to use the whole ALVR all together.
Thank you for your hard work ♥

**Comment by KitsuneShan** [comment]
For the rest of humans like me, does that means that it's fixed? When will we see the next experimental release? I am not avid enough to compile and such :(

**Comment by JackD83** [comment]
I made a release of experimental [v6](https://github.com/JackD83/ALVR/releases/tag/ev6) and hope that its fixes this error

**Comment by DavisNT** [comment]
I can confirm - v6 works well (at least on my PC where v5 always crashed).
