### ISSUE TITLE
12.0.1 Windows ZIP is Showing Having Virus

### ISSUE THREAD

**Issue by raeldor** [JackD83/ALVR#291]
Windows 10 is highlighting the 12.0.1 windows zip as having a virus.

![image](https://user-images.githubusercontent.com/1768444/90110412-21c3eb00-dd88-11ea-9f6d-db5c246da965.png)

**Comment by zingmars** [comment]
Can confirm that after the latest definition update ALVR is marked as a trojan 

![image](https://user-images.githubusercontent.com/917126/90112953-55d3e780-dd59-11ea-98fc-0c08badbcc0d.png)

**Comment by FntstcPlnt** [comment]
Should I be concerned about said "Trojan"?

**Comment by zarik5** [comment]
My guess is that Windows is detecting that sometimes the firewall gets disabled entirely some times after ALVR is downloded. This is because some users do that to diagnose why ALVR does not work.

**Comment by zingmars** [comment]
Looks like Microsoft has fixed the issue and MS defender longer detects the executable as malware. I think the issue can be closed @zarik5.

**Comment by zarik5** [comment]
Thank for reporting!

**Comment by lfrohling** [comment]
Nope. 

My virus checker sees is as a trojsn (Trend Micro Internet Security) - so I would bet money that other virus checkers ALSO see it as such. First Trend tries to stop me running it but if I persist it SAYS it will make it part of it's "trusted" list but it still deletes the file none the less (or at least the "dangerous" part of it). Even on said list downloading a new copy of the file steps you through the same things again- Trend still corrupts the file saying its dangerous and a trojan (and no I'm not going to turn off security to load the file. lol).

**Comment by sctanf** [comment]
Generally third-party antivirus past Windows Defender is unnecessary or even unwanted, the files are safe.

**Comment by Ekristoffe** [comment]
I had this problem with Hitman and the code I compiled myself, some of those soft use heuristic or behavioral, and flag ALVR because it touch the firewall settings and is not well known. because of this it get flagged and sent to other AV company.
I had no trouble with Malwarebyte, Windows defender, Avast, Eset AV.
I may try to look more deeply into this on sunday (If I have some free time to do it) since I know trend micro also have a free online tool.
