### ISSUE TITLE
Add Visual C++ 2019 Redistributable Package to requirenments

### ISSUE THREAD

**Issue by STARasGAMES** [JackD83/ALVR#292]
Today I had a lot of trouble with ALVR streaming to Oculus Quest. It was my first time to do so.
All relevant information is in the link below that helped me resolve the issue.
https://www.qdxingtu.com/key/SteamVR%20Does%20Not%20Detect%20Quest%20Headset%20Over%20ALVR.html

Basically it is required to have Visual C++ 2019 Redistributable Package installed on PC.
It would be great to mention that on requirements or check in the ALVR server application. 

Thanks

**Comment by zarik5** [comment]
The README on this repository already states that you need to install the latest Visual C++ Redistributable Package.
