### ISSUE TITLE
"At alvr\web_server\src\tail.rs:21: The system cannot find the file specified. (os error 2)"

### ISSUE THREAD

**Issue by Pesoen** [JackD83/ALVR#296]
# Please follow the general troubleshooting steps first:

- [X] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

If i try to launch ALVR(regardless where i launch it from) it will display the error message that it crashed, showing the error message in the title. the first time setup was ran at some point, but no session.json was created. recently wanted to play a game in vr and launched ALVR, and this happened. saw there was an update, but the result is the same.

#### Environement

What hardware do you have:
Intel I7-6700k, MSI GTX 1070, Builtin audio on motherboard, and a Corsair Void wireless
What version of ALVR and SteamVR have you tried.
Latest ALVR(and the first v12 release, not one of the beta's)
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number
no, but just today got the option of installing it, due to some "compatibility errors" with my system. installing it ASAP and trying again.

**EDIT**
Updating windows and clearing temporary files seemed to do the trick, it works again. closing the ticket.

**Comment by zarik5** [comment]
Try deleting temporary files with Disk cleanup and restart your PC.

**Comment by Pesoen** [comment]
will try that as soon as the update is installed, at 85%.

**Comment by Winder6** [comment]
@Pesoen same problems, where can i found temporary files?

**Comment by zarik5** [comment]
@Winder6 use Disk Cleanup. Some people had this error persist for a few restarts, but then it fixed itself. If you still have problems write us on the Discord server.

**Comment by Winder6** [comment]
@zarik5 my environment variable of powershell is wrong, it works ater fixing it.

Maybe 'powershell.exe'  can be set to a full path in this line https://github.com/JackD83/ALVR/blob/master/alvr/web_server/src/tail.rs#L13
