### ISSUE TITLE
MIN_IDR_FRAME_INTERVAL

### ISSUE THREAD

**Issue by DavisNT** [JackD83/ALVR#30]
The `MIN_IDR_FRAME_INTERVAL` constant in [alvr_server/IDRScheduler.h](https://github.com/JackD83/ALVR/blob/bb0b9d72d2540070870f9c3b513bc091f1a331c9/alvr_server/IDRScheduler.h#L18) currently is 2 000 000 (2 seconds). 
When packetsloss occurs while streaming fast moving picture the picture gets corrupted ("bluring" artifacts appear) for up to 2 seconds (and very often full 2 seconds). 

I have done some experiments with decreasing this value to 200 000 (200 ms), 100 000 and 40 000. 
I am not sure whether 40 000 was a bit worse than other values, but 100 000 and 200 000 seemed to work very well. 
At least in my setup it looked like glitches happen around as often as with 2 000 000, however picture is restored much faster (usually in less than half second).

Maybe this value should be decreased (to 100 000 or 200 000)?

P.S. Looks like upstream have changed the logic in this commit: 
https://github.com/polygraphene/ALVR/commit/db6f6bbf8a533206a0414861ddd43a61c5b56c6e

**Comment by JackD83** [comment]
I have not yet played with this settings. @polygraphene changed a lot about the handling of idr frames in the commits since the release of his alpha5. Unfortunately, they did not work for me and I had many glitches. That's why the experimental builds are based on the last alpha release.

In theory, you do not need the idr frames at all while the stream is running. Only at the start and at lost frames. The idr frames are a lot larger as normal frames (~10x I think) and sending them could increase the traffic. Maybe we should consider a gui option to  increase the number of IDR frames if someone has problems with the current schedule.

**Comment by DavisNT** [comment]
@JackD83 The `MIN_IDR_FRAME_INTERVAL` constant is used only in [IDRScheduler.cpp](https://github.com/JackD83/ALVR/blob/77dca71f932c00a66168b4b5d77e13c905d52d26/alvr_server/IDRScheduler.cpp) methods OnStreamStart() and OnPacketLoss(). Looks like this constant is **not** used when creating the normal stream. 
However this does increase the traffic during packetsloss - I will do some experimentation with small `MIN_IDR_FRAME_INTERVAL` values and artificially induced packetsloss. According to [wikipedia](https://en.wikipedia.org/wiki/Inter_frame#Frame_types) I frames are around 2-4x bigger than normal. 
I think if increase in traffic during packetsloss will be around 10-20% (with 100 or 200 ms minimum IDR frames interval) then we could just decrease the constant. How do you think?

**Comment by DavisNT** [comment]
Looks like setting `MIN_IDR_FRAME_INTERVAL` to 10 000 and causing 10% packets loss (from PC to headset only) leads to around 20% increase in traffic (however this might depend on video card). 
I think setting this to 100 ms should be safe (and increases usability **a lot** in case of conection instability). 
Also I guess we might make this configurable (for those with unstable connections).

**Comment by JackD83** [comment]
I'm bad with naming things, but a checkbox with "Aggressive recovery" in the other tab would be nice.

I was a little worried about increasing the traffic in a state where we have already packet loss.

**Comment by JackD83** [comment]
@zarik5 intra refresh was enabled by @polygraphene 
It resulted in a lot of artifacts and an overall degraded image quality. The settings are currently unused in VideoEncoderNVENC.cpp. Maybe the switch to Cuda 10 improved it.

@DavisNT I would prefer a checkbox over an input field. Most of the users have no idea what the values represent. A binary choice between a "normal" value and a "fix for bad connection" would be better.

**Comment by JackD83** [comment]
I checked intra refresh again with Cuda 10 and its still bad

**Comment by DavisNT** [comment]
Checkbox "Aggressive keyframe resend" implemented in in [ev7](https://github.com/JackD83/ALVR/releases/tag/ev7).
