### ISSUE TITLE
ALVR desktop keeps ?installing? & pinning edge to the taskbar. - Windows 10

### ISSUE THREAD

**Issue by tokke100** [JackD83/ALVR#305]

**Comment by zarik5** [comment]
It's a bug of Edge. For now you can try uninstalling it. Since Windows blocked the ability to uninstall Edge through Apps & features, you need to use a workaround: https://lifehacker.com/how-to-uninstall-edge-chromium-when-windows-10-wont-let-1844297854 . After that you need to install Chrome if you haven't already.

**Comment by vanclute** [comment]
This is so super annoying.  I couldn't believe it was ALVR doing it but sure enough...  Weird how it's an Edge bug, but no other application makes it reappear in the taskbar for me.  Only ALVR.

**Comment by zarik5** [comment]
@vanclute When I to to renistall Edge Chromium now it fails to install. Can you try an older version of ALVR?

**Comment by zarik5** [comment]
@maxer456 tested this and we concluded that and Edge update is the culprit.

**Comment by tokke100** [comment]
> 
> 
> It's a bug of Edge. For now you can try uninstalling it. Since Windows blocked the ability to uninstall Edge through Apps & features, you need to use a workaround: https://lifehacker.com/how-to-uninstall-edge-chromium-when-windows-10-wont-let-1844297854 . After that you need to install Chrome if you haven't already.

This fixed it. Thanks.

**Comment by eternaldensity** [comment]
Somehow the text encoding at that lifehacker page is all messed up, but this one worked for me: https://mspoweruser.com/how-to-uninstall-microsoft-edge-in-windows-10/

It's bizarre that Edge is causing this issue, but removing it did fix it.  I also had to manually run alvr_web_server.exe from powershell before Windows would pop up the firewall rules dialog to let it actually work.  But now the setup wizard is finally working.

**Comment by alterNERDtive** [comment]
> It's bizarre that Edge is causing this issue

If I had to take a wild guess I’d say that it pins itself to the task bar _literally every time you start it_ and ALVR uses it over Chrome when it’s installed.

But that’s just a wild guess. Never even touched the thing, then had this issue after upgrading to 2004 and removed it again.

Also can confirm that the above thing works.

**Comment by The-Bob** [comment]
Would it be possible to have ALVR use edge as a fallback if no other chromium instance is installed, but to use any other chromium instance over edge?

**Comment by zarik5** [comment]
@The-Bob ALVR uses the Windows API to obtain a webview2 instance (that is a chromium browser). At the end it's Windows OS that decides which browser to use and obviously Windows prefers Edge.

**Comment by maxer456** [comment]
I dug a bit deeper into this.
ALVR uses a library for the webview called [alcro](https://github.com/Srinivasa314/alcro). This library has a list of paths it tries when looking for Chrome, Edge or Chromium (the list is [here](https://github.com/Srinivasa314/alcro/blob/e49071b2b1926f3a293e600c89c4e2da9541205e/src/locate.rs#L33)). Edge is first on the list, so it gets prioritized. That's for the reason why Edge gets chosen even though Chrome is installed as well.

Looking through the code a bit more, alcro launches the Chrome it finds with a few arguments. One of the flags is setting a new user data directory, presumably to not interfere with the user's history, etc. when launching the browser normally. For the launched browser this looks like a first run. Even though first run setup is disabled by one of the arguments (`--no-first-run`), which alcro does supply, Edge just pins itself anyway. You can test this by running Edge with `--no-first-run --user-data-dir="{any non-existent directory}"`.

So it's entirely on Edge for not properly respecting `--no-first-run`. For the preferred browser, alcro would have to change its preference.

**Comment by zarik5** [comment]
Sorry, I really misunderstood how alcro works. I think I got confused with another webview library.

**Comment by maxer456** [comment]
I was thinking of making a PR to just put Edge at the end of the list, since it makes more sense as a system fallback. I can make an issue as well though.
For storing the navigation data, you mean having a persistent user data directory (right now each run gets its own and it gets deleted when closed)?

**Comment by zarik5** [comment]
> For storing the navigation data, you mean having a persistent user data directory (right now each run gets its own and it gets deleted when closed)?

I don't have a clear idea, but basically yes, there could be a configurable folder where to put all navigation and session data. Anyway, ALVR works fine without it, so it's not a priority.

**Comment by maxer456** [comment]
While this isn't completely solved, ALVR server 12.4.0 uses alcro with the mentioned PR and doesn't pin Edge when Chrome is installed.

**Comment by revanmj** [comment]
Tip for users who use Chrome Beta (or any channel other than Stable) - you must create symlink to its Application folder in a stable Chrome path (%LOCALAPPDATA%\Google\Chrome) for ALVR to use it instead of Edge.
