### ISSUE TITLE
Driver registration problem on multi-byte path

### ISSUE THREAD

**Issue by KawaSwitch** [JackD83/ALVR#307]
- [x] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

Removing drivers fails when a multi byte characters are included in the path as I mentioned [here](https://github.com/JackD83/ALVR/issues/281#issuecomment-686899589).
I can only add drivers and can't remove them after that.

![alvr_garbled](https://user-images.githubusercontent.com/41296626/94352130-29232780-009c-11eb-893f-ea64a7a42dea.PNG)

#### Environement

CPU: Intel Core i7-6700
GPU: GeForce GTX 1660 Ti
ALVR: server v12.2.0 (release / master head), client v12.0.0
SteamVR: 1.14.16
Windows 10: 2004

### Features:

I noticed that alvr uses vrpathreg.exe in registration process so I've tried the same thing on powershell and it shows a somewhat different behavior than what happened with alvr.

Here's more details with screenshots. In the Japanese version of Windows 10, the default character code of powershell is Shift-JIS (CP935). The path is shown correclty after I registered it on alvr.

![shift_jis](https://user-images.githubusercontent.com/41296626/94352133-34765300-009c-11eb-812c-be4e378899f1.PNG)

Then I switch from Shift-JIS to UTF-8, it shows the garbled characters as shown below.

![utf](https://user-images.githubusercontent.com/41296626/94352136-36d8ad00-009c-11eb-8c2b-16496dc68e98.PNG)

It is possible to remove this driver if I input the path directly on powershell, on either UTF-8 or shift-jis. In UTF-8, the input string is also garbled though.

![utf_removing](https://user-images.githubusercontent.com/41296626/94352258-9e432c80-009d-11eb-9c24-4af9b03f30d1.PNG)

On chrome, it's also garbled.

![utf_on_chrome](https://user-images.githubusercontent.com/41296626/94352272-c03caf00-009d-11eb-9a0e-1be00de9931b.PNG)

Still the same even if I transformed it into shift-jis using a chrome extension.

![shift_jis_on_chrome](https://user-images.githubusercontent.com/41296626/94352296-fed26980-009d-11eb-944e-3bcfde2bbb88.PNG)

If you enter a path that doesn't exist like below, you won't be told anything unless the absolute path is collapsed, so I think this is  kind of related to this unremovable issue.

![try_error](https://user-images.githubusercontent.com/41296626/94352663-ee70bd80-00a2-11eb-9082-20b46c9a01e6.PNG)

Any ideas?

**Comment by KawaSwitch** [comment]
And I've noticed that it seems like SteamVR doesn't work when registering the path including Japanese (maybe multi-byte?). It keeps saying "Standing by" and shows laggy alvr space in HMD while it doesn't occur when registering ascii path.

It's like a problem with OpenVR/SteamVR though...

**Comment by zarik5** [comment]
Thanks for opening the issue (I forgot about it). Can you try adding the driver path directly to `%LOCALAPPDATA%\openvr\openvrpaths.vrpath` (under "external_drivers") and see if ALVR starts correctly? The dev branch for ALVR v13 does this (branch `sockets-rewrite`).

**Comment by KawaSwitch** [comment]
Sorry to late since the last issue. I switched the branch and tried both ascii and Japanese paths as you told. In Japanese case, ALVR keeps saying "Waiting for driver to load" and can't even get to the dashboard, and SteamVR says "Standing by".

English
![set_english_directly](https://user-images.githubusercontent.com/41296626/94367699-519e3680-011b-11eb-986b-57aa4b2bdeaf.PNG)

Japanese
![set_japanese_directly](https://user-images.githubusercontent.com/41296626/94367707-55ca5400-011b-11eb-8c38-1d01b834abe9.PNG)

**Comment by zarik5** [comment]
Since you set the path directly into the OpenVR config file and it didn't work, I'm afraid there's nothing we can do. Hopefully it would not be a problem to use only UTF-8 chars for ALVR driver path.

**Comment by KawaSwitch** [comment]
Ok I got it.
