### ISSUE TITLE
I want to change Ports

### ISSUE THREAD

**Issue by E2VRTanguy** [JackD83/ALVR#308]
Hello I want to change the Hello Port and the Listen Port I know how to change them in the client but I can't found them on the new version of the server
Can someone help me please

**Comment by zarik5** [comment]
The Hello port cannot be changed. The listen port can be changed in the next major version (no ETA for now).

**Comment by E2VRTanguy** [comment]
ok thank you for the reply

**Comment by E2VRTanguy** [comment]
Just even in the code I can't change the Hello port and the Listen Port @zarik5

**Comment by zarik5** [comment]
Maybe they are hardcoded in multiple places. In the next version the connection and streaming system is completely replaced so this issue will be solved.

**Comment by E2VRTanguy** [comment]
ok thanks for the reply I will continue to search them
