### ISSUE TITLE
Blank ALVR GUI

### ISSUE THREAD

**Issue by JaiMcD** [JackD83/ALVR#309]
### Bug reports:

When opening the ALVR exe on my pc it opens, however where the gui is supposed to be it is just a blank white screen

#### Environement

Intel i5, NVIDIA 2060
Latest Version of both steamVR and ALVR 
windows 19041.508

**Comment by zarik5** [comment]
That could be caused by no output audio devices detected.

**Comment by JaiMcD** [comment]
> That could be caused by no output audio devices detected.

That was it, I connected my speaker and it worked fine. Thankyou!
