### ISSUE TITLE
Feature Request: generic device as Quest mic monitor

### ISSUE THREAD

**Issue by alterNERDtive** [JackD83/ALVR#310]
Right now the supported way of getting the Quest mic to be streamed back to the PC is using VB Audio Cable.

It would be great if you could just choose any arbitrary device like you can for audio playback on the Quest. E.g. in my case I use a similar tool and don’t really want to install VA Cable on top.

FYI: Current workaround according to @maxer456 is renaming the cable device to something containing `CABLE` since looking for that is the elaborate detection algorithm (haven’t tried it yet) :)

**Comment by maxer456** [comment]
Thanks for the feedback! This is now implemented in ALVR server 12.4.0.
