### ISSUE TITLE
SteamVR through Link not working after trying ALVR

### ISSUE THREAD

**Issue by antonioxdias** [JackD83/ALVR#312]
Hey hey! Hope i'm not polluting the repo, but i found nowhere else to ask.

So i successfully installed and ran ALVR on my quest. The software worked great out of the box!, but my current wireless setup is not good enough to give a proper experience. Will be revisiting ALVR when it does.

The problem is, since i tried this, i can no longer use SteamVR via oculus link. When i open the app in the oculus home, it starts loading but nothing happens.

Hopefully cleaning up something that ALVR modified can fix the issue?

Windows 10 x64 , i5-8600k, gtx 1660 ti.

Thanks in advance!

**Comment by The-Bob** [comment]
I'd try removing the ALVR server driver. It's under "Installation" in ALVR menus.

For the future, there's a discord server: https://discord.com/invite/KbKk3UM

**Comment by antonioxdias** [comment]
Thanks @The-Bob for the quick reply! I'll try this soon. Also thanks for the discord link, any further questions i'll just ask there.
