### ISSUE TITLE
Request default audio device

### ISSUE THREAD

**Issue by DocMAX** [JackD83/ALVR#314]
I would like to see ALVR taking whatever audio device is currently default and take it for audio and mute it, whenever the headset is active. Without manually setting it up in the config tool.

**Comment by alterNERDtive** [comment]
> I would like to see ALVR taking whatever audio device is currently default

Isn’t taking the default device already the default? I vaguely remember having to change it from that.

> and take it for audio and mute it

If you mute it monitoring it will give you no audio, AFAIK.

Also what’s your use case? Sounds not standard → shouldn’t be default.

**Comment by DocMAX** [comment]
indeed it's not standard (virtualized machine in qemu kvm with gpu passthrough, running on different machines with different audio setup).
if i mute the audio source, i still can hear on ALVR.
