### ISSUE TITLE
Best settings ALVR / Quest 2?

### ISSUE THREAD

**Issue by Asryan2a** [JackD83/ALVR#316]
Hi,

I got a quest 2 recently (like everyone) and i tried Virtual Desktop at first but it wasn't good at all, stutters and all..

I decided to go with ALVR and all is wayyy better.

i have an internet box, the one from my provider which is onlu wifi5

My wifi 5ghz and 2,4 are separated, i have a 1gb fiber, 300Mo on wifi

i see there is A LOT of parameters in ALVR and I wanted to know what would be the best settings?

What about :

Video resolution? I put 150%Codec? Went with H264bitrate video? l put it on 90

Also i can't find how to set up audio to have sound in the headset but NOT on the pc? also the sound is a bit low

Thanks for the help !

**Comment by zarik5** [comment]
The ALVR devs don't have yet the Oculus Quest 2, you should ask in the discord server https://discord.gg/KbKk3UM

**Comment by bennodxb** [comment]
Im no expert, but afaik you want to use h265 for superior quality and latency if your CPU can support the decoding.

I also cant have audio just from headset, If i mute on the PC it works though but too quiet as you say.
