### ISSUE TITLE
IPD adjustments not working on Quest 2

### ISSUE THREAD

**Issue by phly95** [JackD83/ALVR#318]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

I first started ALVR with the #2 IPD setting on the Quest 2. I later switched to #3 as that is more my size. But now when I use ALVR, everything looks all cross-eyed, and it hurts to look at anything. The IPD should automatically adjust when changing the setting on the headset.

#### Environment

What hardware do you have: Intel i7 4790, Nvidia GTX 1060 6GB
ALVR Server: 12.4.1, SteamVR: 1.14.16, not sure how to check app version
Windows 10 version: 1909

**Comment by Espionage724** [comment]
> But now when I use ALVR, everything looks all cross-eyed, and it hurts to look at anything. 

I'd almost say that's an understatement; I don't think even my first locomotion game experience was anywhere as bad as ALVR was when I started it up on IPD 3. The discomfort hit me within seconds.

Switching the IPD to 2 seemingly works fine though, but 3 is also more my size.

**Comment by zarik5** [comment]
The fix is coming next week on v12.5.0

**Comment by dnviti** [comment]
This problem has not yet being fixed on the Pre-release. Could the IPD adjustment just be manual?

**Comment by zarik5** [comment]
We're working on it. For now just use v12.4.1
