### ISSUE TITLE
No line for "show advanced options" description localization 

### ISSUE THREAD

**Issue by 5he1n** [JackD83/ALVR#319]
Was translating ALVR, found a not ttranslatable line. 
"show advanced options" _description_ for "toggleAdvanced" _toggle_ in main.js
Same issue for all localizations.

![Screenshot](https://user-images.githubusercontent.com/49807893/96372775-38fccb80-1171-11eb-9045-c123c6e0df77.png)

**Comment by zarik5** [comment]
I removed the tooltip
