### ISSUE TITLE
NEON optimization?

### ISSUE THREAD

**Issue by Sztrovacsek81** [JackD83/ALVR#32]
Hello Team,

It is possible that ALVR is not using any NEON video decoding optimization in client side?
I have searched the source code but didn't find anything related to it.
The greatest lag come from the client side decoding, it would be nice to lower this lag through optimization.
This is an av1 example, but it has great potential:
https://medium.com/@ewoutterhoeven/how-arms-neon-enables-efficient-av1-decoding-on-mobile-5fcb3a4f6e7f
Thank you!

**Comment by JackD83** [comment]
The client is currently using android.media.MediaCodec to decode the video. 
NEON and dav1d could be a great improvement, but I probably lack the skills to do it myself :(

**Comment by JackD83** [comment]
After reading a little about this topic, I'm pretty sure the decoder is already using this kind of optimization. There are some papers describing this in 2013 [here](https://ieeexplore.ieee.org/document/7056307)

After seeing the results back then (720p (1280x720) streams at 30 frames per second) I think this is used to decode our 3k stream at 72fps

The new part with dav1d is that its used for AV1

**Comment by Sztrovacsek81** [comment]
I have some error regarding gradle in android studio.
Could you edit the build.gradle like this and test it:

externalNativeBuild {
            cmake {
                arguments "-DANDROID_ARM_NEON=ON"
                cppFlags ""
            }
        }

**Comment by Sztrovacsek81** [comment]
I think I was misleaded by this AV1 experiment (there is no hardware AV1 decoder yet).

**Comment by JackD83** [comment]
I think that the flag `-DANDROID_ARM_NEON=ON` has only influence on our own code that does not profit from the optimization
