### ISSUE TITLE
Never used lines

### ISSUE THREAD

**Issue by 5he1n** [JackD83/ALVR#322]
During translation found at least 3 never used lines
It`s presented in code, but not in the UI

_root_headset_controllers_content_positionOffsetLeft.description
_root_headset_controllers_content_rotationOffsetLeft.description
_root_video_codec-choice-.description
![Pic](https://user-images.githubusercontent.com/49807893/96696750-ccade200-1393-11eb-8c78-b6b9df37bf4e.png)
![PIc](https://user-images.githubusercontent.com/49807893/96696915-fcf58080-1393-11eb-9bcc-78e809af33f8.png)

**Comment by zarik5** [comment]
Fixed.
