### ISSUE TITLE
Doublevision on Quest 2

### ISSUE THREAD

**Issue by sorola117** [JackD83/ALVR#324]
### Bug reports:

Server launches fine with no latency or issues, except for severe double vision. Different IPD settings dont help, I normally play on the smallest IPD and still have really bad doublevision through ALVR

**Comment by zarik5** [comment]
@sorola117 try ALVR v12.5. You need to install the client from GitHub. People report that it doesn't work immediately, try restarting the quest after moving the lenses.

**Comment by dnviti** [comment]
i can confirm, using the latest apk 12.5.0 and the latest server version and IPD from the Oculus Quest 2 is completely ignored.
The server sets it on 0.065 and there is NO WAY to change that.
For me it is unplayable like this, do we REALLY need to automatically set that? I'm perfectly fine with a manual IPD setting, at least give us the choise whether to autoset or manual...

**Comment by kmclaughlinphd** [comment]
It worked for me. I prefer IPD 68. I have it set to 0.068 in video advanced options.

When I first launched and connected, I had bad double vision. I clicked the lenses in to 63, then back to 68, and it's perfect. Maybe try to see if that helps you.

**Comment by kmclaughlinphd** [comment]
This still occurs on 12.5 when in the steam overlay window (press menu button while in game) and loading screens.

**Comment by zarik5** [comment]
@kmclaughlinphd I think this is a bug with SteamVR. Do this happens also with the Oculus Link?

**Comment by kmclaughlinphd** [comment]
it does not happen with the oculus link, and to my memory it did not happen on the previous ALVR release version when on 63mm. 

If it's helpful, I can check if it's only an issue when on 68mm in ALVR.

**Comment by zarik5** [comment]
@kmclaughlinphd Can you make one more check? On Oculus Link, what happens when you change IPD without taking the headset off? If you look at the floor and trigger the guardian boundary, does the perimeter stays at floor level or does it goes down or up?

**Comment by kmclaughlinphd** [comment]
on oculus link + steamvr:

keeping headset on and clicking IPD: view successfully recalibrates after <1s delay
looking at the floor, the perimeter is stable

I checked while in the main steamvr lobby/game selection screen, and again with the steam menu overlay up. (sorry if my terminology isn't very precise)

**Comment by zarik5** [comment]
I'll ask @maxer456 if he can help.

**Comment by TheYoshiGangsta** [comment]
I had a friend having this exact issue and right now he fixed it. He had a duplicate folder of the drivers on his desktop. He removed the folder from his desktop and redid the installation with a confirmed ONE folder of ALVR and it's drivers and it's working for him, try that. :)

**Comment by kmclaughlinphd** [comment]
only one folder here

**Comment by maxer456** [comment]
Is the view just cross-eyed (or double vision) - incorrect IPD? If the image doesn't warp when tilting your head, it could be that we're just not setting IPD everywhere we should. I'm asking about image warping because that would probably be incorrect FoV and that gets set basically just one way.

I'll see if I can reproduce it on Q1 (don't have Quest 2), though it'll probably be harder to notice. Anyway, there's at least two places to set IPD (I'm guessing the function we currently use for setting IPD sets just one), one of which is a SteamVR (as in that's part of the name) setting, so that might be it, considering you only see the issue in SteamVR spaces (see [this line](https://github.com/JackD83/ALVR/blob/8cc5af2ee9de1eb09a848bdd8394dfdd1e6fffd0/alvr/server_driver/cpp/alvr_server/OvrHMD.cpp#L126)). It would also make sense why it didn't happen on previous releases, since the way we set the current IPD changed.

**Comment by kmclaughlinphd** [comment]
to clarify, I'm specifically talking about the steamvr overlay menu (left-controller menu click) and loading screen dialog. no issue in game/lobby.

1. it's reversed cross-eyed, I guess: my eyes are needing to point uncomfortably outwards to compensate
2. the image does warp as well, in a similar manner to the warpage at the 58mm headset setting
3. if I click my headset to 63mm, the overlay menu does NOT warp --- I believe this is inline with your suspicion above




what you're saying about setting the IPD makes sense, I think.

**Comment by maxer456** [comment]
I can't reproduce this on the Q1, unfortunately. On 12.5.0 you can try setting IPD as before in advanced options. It will get used on startup before the Quest sends its current values and set the SteamVR setting I mentioned.
Next release will also set the SteamVR IPD setting when changing IPD. If you can build ALVR server, you can try testing the master branch. I'm not sure about the warping though.

**Comment by kmclaughlinphd** [comment]
I have already set the IPD in the advanced options. It's not a show stopper, so I will wait for the next release, and report back.

**Comment by zarik5** [comment]
@maxer456 I tested your changes but the SteamVR HUD still appears doubled and it skews when I tilt my head, so not even the FOV is synchronized.

**Comment by zarik5** [comment]
Doing some more tests on the Quest 2 it seems that the problem is only related to FOV.

**Comment by kmclaughlinphd** [comment]
I'm on 12.5.1 now. HUD looks good for me on 68mm now. Excellent!

**Comment by maxer456** [comment]
Thanks for confirming! I think that's all of the double vision issues.
