### ISSUE TITLE
Intel Quick Sync support

### ISSUE THREAD

**Issue by BSoD38** [JackD83/ALVR#327]
#### Environement
Intel i7 8700k + RTX 2080 Super

### Features:

Adding Intel QuickSync support would help offloading video encoding work to my iGPU, and dedicate all of my GPU's resources to the game. I use this trick on OBS Studio to avoid encoder overloading and game performance issues.

Has this ever been looked on ?

**Comment by zarik5** [comment]
This will come with #243.
