### ISSUE TITLE
ALVR allow us to use the high bandwidtch USB C connection to use the quest as a PC VR headset

### ISSUE THREAD

**Issue by ancarvmed** [JackD83/ALVR#33]
ALVR allow us to use the high bandwidtch USB C connection to use the quest as a PC VR headset

can do it?

**Comment by ancarvmed** [comment]
Here's a tweet from the developer of iVRy, which is another program for streaming PCVR to the quest. He states that USB is working. https://twitter.com/iVRy_VR/status/1131238363367858176?s=20

**Comment by JackD83** [comment]
The keyword would be "reverse tethering" if you get this working on the quest, it can be used as a connection for alvr without any changes. I read that there was a half working solution for the oculus go.  

Programs like [srcpy](https://github.com/Genymobile/scrcpy) also work using adb

Be aware that the usb connection on the quest was not designed for that use. One bad movement and you will rip it apart

**Comment by DavisNT** [comment]
Another option might be using USB ethernet adapter (if that is supported by Oculus Quest). 
I agree about the risks with USB connection (especially with straight and long connectors). There are magnetic USB-C connectors that could help (however the magnetic connectors with data lines are not very cheap).

**Comment by KitsuneShan** [comment]
Quest cable it's pretty long and you can use some velcro to secure the cable and avoid any damage to the connector. Anyway this is something secondary. The main thing it's being able to do so, wether someone may break it or not it's a responsability of each one of us on taking care while doing it this way.

**Comment by Entropy512** [comment]
MJPEG would likely be too high bitrate.

And it's questionable whether or not properly configured H.264 (bframes disabled, minimal buffering) would actually be any better.  There's a good chance that to avoid jitter/duped frames you'd have to have 1-2 frames of MJPEG buffer anyway.

IIRC, DJI was still only able to get down to 28ms by transmitting lower-res 120FPS for a recently announced FPV racing product, which translates to roughly 3 frames of latency at that framerate.

**Comment by JackD83** [comment]
I think MJPEG will never happen without any kind of hardware acceleration. Both the gpuon the server and on the hmd have optimized hardware implementations for h264 and h265 that are used right now. 
I think the only benefit of a cable would be the rock solid connection without any dropped frames. The tracking could also benefit from the reduced latency.

**Comment by fsiefken** [comment]
reverse tethetring might work with gnirehtet
https://github.com/Genymobile/gnirehtet
https://www.reddit.com/r/OculusGo/comments/ci54o8/how_to_internet_with_nobad_wifi/

**Comment by JackD83** [comment]
I think with the announcement of the Oculus Quest Link, all this is obsolete. Just wait for the November update and use the official software.

**Comment by SnyderTheOne** [comment]
Sadly, but also happily, yes. But I still commend you for trying to keep this project up to date untill now!

**Comment by JackD83** [comment]
As long as oculus does not announce a wireless solution, ALVR is still kicking :) 
My gaming pc is in another room, a cable would be way to short

**Comment by JackD83** [comment]
Link is available. If you want to play tethered, use Oculus Link
