### ISSUE TITLE
12.5.0 pre2 reduces my FPS in games vs 12.4.1

### ISSUE THREAD

**Issue by RickAndTired** [JackD83/ALVR#332]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

12.5.0 pre2 reduces my FPS in games vs 12.4.1

With ALVR 12.4.1 I get a steady 72fps in Half-Life Alyx
With ALVR 12.5.0 pre1 and pre2 I get 40-55fps in Half-Life Alyx

I tested the very start of Half-Life Alyx three times with each version getting the same results
I chose the same settings running the ALVR setup wizard and used the same bitrate 
No other settings changed

#### Environement

What hardware do you have: Ryzen 5 2600, RX 570
What version of ALVR and SteamVR have you tried: 12.4.1, 12.5.0 pre1, pre2
Do you have the latest Windows updates? Yes

**Comment by fezboy** [comment]
In 484e9a4, @JackD83 corrected the resolution for the quest 2, which is higher than the quest 1. I'd probably blame that. You might try turning down the resolution scale.

**Comment by RickAndTired** [comment]
Looks like that might have been it, thank you
