### ISSUE TITLE
At alvr\web_server\src\tail.rs:21: The system cannot find the file specified. (os error 2)

### ISSUE THREAD

**Issue by jlawrence124** [JackD83/ALVR#343]
# Please follow the general troubleshooting steps first:

- [ X ] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [ X ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Starting at ALVR 12.0 I get the following error when launching.

At alvr\web_server\src\tail.rs:21: The system cannot find the file specified. (os error 2)

I have tried to clear temporary files with disk utility as I found in a previous issue report.

I installed correct VS Redist package, have steam vr updated and installed, and ALVR is on my quest.

#### Environement

What hardware do you have: CPU, GPU, Audio

- Intel i7-7700k

- MSI GTX 1080

- MSI HERO Maximus IX onboard audio

What version of ALVR and SteamVR have you tried. 

- ALVR version 12.5.1

- Steam VR 1.14.16

Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number

- Latest windows updates have been installed. On version 19041.610

**Comment by zarik5** [comment]
We cannot find the cause of this bug. For some people the problem went away on its own, but if it still persist then use ALVR v11.

**Comment by zarik5** [comment]
This might help you: https://github.com/JackD83/ALVR/issues/296#issuecomment-716280058
Try adding "Powershell.exe" to the PATH environment variable

**Comment by maxer456** [comment]
Should we make this issue non-fatal and display a warning instead of crashing?

**Comment by zarik5** [comment]
@maxer456 ok, you can implement that if you want.

**Comment by maxer456** [comment]
Tested this some more and it turns out only powershell.exe missing from path (or otherwise system failing to run it) triggers this error. Powershell itself failing to open the log file does not.

**Comment by maxer456** [comment]
Starting 12.6.0, this will now only produce a warning message and not crash the application.
