### ISSUE TITLE
need help fixing "headset not detected"

### ISSUE THREAD

**Issue by colrobloxkid69420** [JackD83/ALVR#346]
need help fixing "headset not detected"
Here is a screenshot I took (as you can see there is no alvr add on in steamvr which from what I've seen is supposed to be there)
![Capture](https://user-images.githubusercontent.com/73903938/98080869-d26cf280-1e7e-11eb-9150-a4b0a10cbeec.PNG)
And in debug.log it wrote: [1103/135130.737:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)

#### Environement

I have the acer predator helios 300
both the apk file and the computer file are 12.5.0
I have windows 10 version 1909

**Comment by zarik5** [comment]
If you didn't already, read the [troubleshooting page](https://github.com/JackD83/ALVR/wiki/Troubleshooting-(for-ALVR-12.0.0-and-later). If you need further assistance, send a message in the discord server.
