### ISSUE TITLE
Add Windows Mixed reality Support

### ISSUE THREAD

**Issue by cschultz099** [JackD83/ALVR#348]
This could potentially be a huge step in the difference between ALVR and the possibly upcoming wireless oculus link. This would offer a bigger variety of games to be played like for example, Minecraft bedrock edition, Halo Recruit, etc. that can be accessed in the windows mixed reality portal.

**Comment by Nexite** [comment]
just wait, soon there will probably be a steamvr to wmr portal translator and it will probably work better than whatever we implement

**Comment by lmarianski** [comment]
Yeah a WMR-SteamVR bridge would probably be better than adding WMR to ALRV directly

**Comment by zarik5** [comment]
The Windows Mixed Reality runtime does not offer an API to build device drivers, so support on ALVR is just not possible. We need a more advanced third party tool for the SteamVR-WMR bridge, but since the WMR ecosystem is much smaller than SteamVR, this may never happen.

**Comment by cschultz099** [comment]
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/device-portal-api-reference

**Comment by lmarianski** [comment]
As far as I can tell this just allows you to control a WMR-enabled device from a computer, kind of like their version of ADB.
