### ISSUE TITLE
Enabling microphone skyrockets latency

### ISSUE THREAD

**Issue by aerosc** [JackD83/ALVR#35]
Hello, thank you for the great work! I am using latest experimental v5 version. When I enable microphone streaming after a few minutes transport and decode latency increases and it becomes unplayable (see the pic.). My PC is connected with ethernet cable and I share wifi with a 5 Ghz usb dongle. When I disable microphone the problem is gone.

![Adsız](https://user-images.githubusercontent.com/55176600/64671470-378ea900-d471-11e9-988d-72dde088373e.png)

**Comment by JackD83** [comment]
Unfortunately, its not only the microphone, its just happens more often if mic streaming is used. 
Its the same error as #6

**Comment by JackD83** [comment]
@aerosc could you please test release experimental [v6](https://github.com/JackD83/ALVR/releases/tag/ev6)?

**Comment by aerosc** [comment]
I have tested it with Pavlov again. The ping spiking when I enable microphone is gone. However, there is regular stutter/freeze/lag. It happens every 10-15 seconds, transport latency increases to 200-1000ms (pic.) then drops back to normal in 1-2 seconds. I tried enabling/disabling mic., played with bitrate and codec, but it didn't help. The smoothness of v5 is gone.
Also, dont know if it was intended but sound streaming option is gone. Instead, it says 'No sound devices are found'.
![alvr_ev6](https://user-images.githubusercontent.com/55176600/64880439-df1dfe00-d660-11e9-9fa3-5c0eaade4e0a.jpg)

**Comment by JackD83** [comment]
> The smoothness of v5 is gone

There was no change in network code. The major lag was possibly caused by a buffer that was too small.  
For your current issue I suspect a problem with your network or some antivirus software. I don't own Pavlov, but my tests are very smooth with other games.

The 'No sound devices are found' message is indeed a new bug

**Comment by ShodanOne** [comment]
@jackD83,
I’m just curious to know what 5g routeur model you use. Is your dedicated to the quest ?

**Comment by JackD83** [comment]
I used a no name router from my ISP, but it had its problems with port forwarding. Streaming was ok.
I recently bought a Tenda AC9 AC1200 to have a dedicated wifi for the qurest, It works fine but it is missing many options. I was under the wrong impression that the router supported openWRT.

I think the most important part is to lower the channel width to 40Mhz and choose a free 5Ghz channel.
Having it in the same room should help too.

**Comment by aerosc** [comment]
> There was no change in network code. The major lag was possibly caused by a buffer that was too small.
Yes, increasing buffer size helped, thank you.
