### ISSUE TITLE
"Update in Progress" message when opening the app

### ISSUE THREAD

**Issue by amg-12** [JackD83/ALVR#4]
Every time I try to launch the app on the headset it gives an "Update in Progress" message and the app does not launch. Other apps including sideloaded ones do work.

**Comment by amg-12** [comment]
Solved by enabling updates on my headset and letting it update. For the future, please mention version compatibility in the readme.

**Comment by JackD83** [comment]
Readme is a copy from ALVR, I have to update it in the future
