### ISSUE TITLE
Setting server IP in ALVRClient works only while running

### ISSUE THREAD

**Issue by DavisNT** [JackD83/ALVR#40]
Setting server IP in ALVRClient while it is not running causes a crash. I will fix this. 

Workaround is to start ALVRClient and set the server IP while ALVRClient is running. ALVRClient needs to be restarted for the setting to take effect.

**Comment by lorenzinfantino** [comment]
I have a question, no matter what IP I set my client is never seen by the server, obviously I'm doing something wrong...

**Comment by DavisNT** [comment]
@lorenzinfantino Have you done all the necessary firewall openings? 
The UDP ports 9943 and 9944 must be opened on the server (and all firewalls between client and server), so the client can "connect" there.

**Comment by lorenzinfantino** [comment]
@DavisNT Yup, i went into the firewall settings and added rules for those ports, but still nothing happens, maybe i need to do something on the client other than setting the IP?

**Comment by DavisNT** [comment]
@lorenzinfantino Nohing else should be done on client (apart from opening it, connecting headset to PC, running the command line on PC, restarting the client). 
You can try to troubleshoot the connectivity issue as described here: https://github.com/polygraphene/ALVR/wiki/Troubleshooting#ip-address-is-not-displayed-on-alvrexe

**Comment by lorenzinfantino** [comment]
I'll try to troubleshoot later today, but if I connet the oculus to the same wifi the servers sees the client, so I guess my ports are fine and working, as soon as I try to change the wifi on the oculus (staying on the same network, just a different subnet) it disappear. Maybe I'm missing the point of the IP change but to my understanding, and correct me if I'm wrong, it's supposed to make the oculus connect to the server even from a different network...

**Comment by DavisNT** [comment]
@lorenzinfantino To be able to connect to ALVR server from a different network both networks must be connected (UDP ports 9943 and 9944 of ALVR server must be reachable by ALVR client). I.e. The ALVR server must be reachable (e.g. pingable) from the network where ALVR client is connected.

**Comment by DavisNT** [comment]
Pull request fixing this issue has been submitted https://github.com/JackD83/ALVRClient/pull/2

**Comment by DavisNT** [comment]
Fixed in [ev7](https://github.com/JackD83/ALVR/releases/tag/ev7).
