### ISSUE TITLE
How to setup microphone

### ISSUE THREAD

**Issue by kgian** [JackD83/ALVR#41]
Hello, thanks for your great work. 

I cannot get microphone audio to work. I have install virtual cable driver. On ALVR first run in quest I have accepted microphone permissions.

In ALVR windows app I ahve checked "stream quest microphone"

In windows control panel-->manage audio devices I have : Playback Speakers Realtek high definiton audio
and recording: Cable output VB audio virtual cable set as default device and default communication device.

In steamVR settings I have 
When using steam VR

Set playback device to (do not change)
Set record device to Cable output

Despite all this microphone seems to not be working. At least no one answers me when I ask them. Is something wrong with my setup and is there any easy way to test my microphone?

**Comment by JackD83** [comment]
Your settings seem correct. Maybe "CABLE input" is somehow muted? "Cable output" should work as a normal mic in any application like Sype etc.

What ALVR does is record the mic on the hmd and then play the sound on the "CABLE input" speaker which then transmits it to the virtual microphone "CABLE output"

This is done to avoid writing our own windows driver. So if you know how to do that, please contact us and help make ALVR better!

**Comment by kgian** [comment]
I have not done anything with or set anywhere cable input. I will check it with skype test call and report back my findings.
