### ISSUE TITLE
Experimental v6 Client crash on Quest

### ISSUE THREAD

**Issue by itolson** [JackD83/ALVR#42]
Hi,

I have installed the latest server and client Experimental v6 and when I open in on the quest it opens the Steamvr world without the menu etc and then closes.

The server says client is connected and it was working fine last night.

Thanks

**Comment by JackD83** [comment]
You could try to reinstall alvr on the quest:
- uninstall with `adb uninstall com.polygraphene.alvr`
- install as usual

I never had an issue like this

**Comment by JackD83** [comment]
closed due to inactivity
