### ISSUE TITLE
Optimal FFR Settings

### ISSUE THREAD

**Issue by Digeeboy** [JackD83/ALVR#43]
Can't say I fully understand the tech behind FFR but would appreciate any pointers to setting the option values for a reasonably high PC.  i7 8700K and gtx1080ti

**Comment by JackD83** [comment]
That depends on your perception. You should try different settings going from foveationStrengthMean= 2 up to 5. You can use any fraction you like (2.25...)
The higher you go, the more visual artifacts you will see at the edges of the screen. 

FFR adds a little blur to the image you can compensate by setting the initial video resolution to 125%. This, hopefully, wont be necessary in the future.

I personally use a video resolution of 125% and FFR 4. 

Btw, your pc specs don't have much influence on the FFR. Rendering resolution stays the same, its the video resolution that is reduced which in the end, results in a faster encoding and decoding and less latency

**Comment by JackD83** [comment]
I made a wiki page: [wiki](https://github.com/JackD83/ALVR/wiki/FFR)
