### ISSUE TITLE
"Press Connect Button" on Experimental V6

### ISSUE THREAD

**Issue by steve30avs** [JackD83/ALVR#44]
Hello,

When running the Experimental V6 release, the client will say "Press Connect Button" to continue. On the server end, it finds the headset and starts the server successfully, but only shows 1 packet going through and all the activity sets to 0.

I reverted to v5 and everything works fine.

**Comment by JackD83** [comment]
I had this once. There was something stuck on the Quest or in steam VR. Could you please try to uninstall both, the driver on the PC and the quest application and start over?

**Comment by steve30avs** [comment]
Works now, thanks for the tips.
I uninstalled the APK, SteamVR, and the driver and reinstalled all 3.
