### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by Avencore** [JackD83/ALVR#45]
Whenever I try to start the server I get the following error:

Failed to start audio capture. Thread aborted before starting to loopback capture. message=IAudioClient::Initialize failed: hr = 0x88890008

I have already tried to set the system sound to 16bit,48000Hz(DVD) as suggested in other issues but it didn't help. Unchecking steam sound helps. I'm on experimental v6.

Greetings,
Avencore

**Comment by JackD83** [comment]
Do you have a usb audio device? If yes, could you try to disconnect it?

**Comment by Avencore** [comment]
No I don't. I disconnected all audio devices aswell as my monitor with speakers and still the same error message.

**Comment by JackD83** [comment]
>  my monitor with speakers
Do you by any chance use the remote desktop to launch ALVR on your PC? Cause that is not working. I had to use TeamView to access my PC in the other  room

**Comment by Avencore** [comment]
I'm not sure what you mean by remote desktop.
My procedure for starting is the following:
Start ALVR programm on PC
Start ALVR on Quest
-quest connects to pc automatically-
Press Trigger on Quest to start server/steamVr
Error message on PC appears
Quest app crashes

**Comment by JackD83** [comment]
Ok, I was just wondering how you start ALVR without a monitor.
What audio devices do you have? ALVR tries to capture the audio at 48khz 16bit, the error you get suggests that this is not supported by your audio device. After a little research, I found that Realtek audio drivers sometimes misbehave in that regard. Maybe there is an updated driver for your hardware.

You can also enable ALVR debut log. Create the folder „logs“ next to your ALVR.exe
In the Uli under debug, you can enable the logging. Please post the log here.

**Comment by Avencore** [comment]
Thank you for your time. Updating the Realtek driver indeed fixed the issue.
