### ISSUE TITLE
REQUEST: Pass Quest's Guardian info to SteamVR

### ISSUE THREAD

**Issue by wesbeyrent** [JackD83/ALVR#49]
I have to redo the room setup for SteamVR every time I launch.  Is there some way you can pass the Quest's Guardian data into SteamVR the way that Virtual Desktop does it?

**Comment by JackD83** [comment]
No, no need for that. You have to calibrate your room in SteamVR as "standing". I made a new Wiki entry:
[Room Setup](https://github.com/JackD83/ALVR/wiki/Room-Setup)
