### ISSUE TITLE
Holding controller upside-down flips the controls

### ISSUE THREAD

**Issue by RobbeSchepens** [JackD83/ALVR#5]
Hi, 

I'm playing No Man's Sky. You can use the left joystick to move around. When I hold the joystick forward to walk forward, it walks forward as expected. But when you keep holding it forward and you hold the controller upside-down, your character starts walking backwards as if it flips the controls. 

I asked my friend who was playing with me and using Virtual Desktop to do the same, but for him those controls don't flip around so I assume this is a wrong implementation in ALVR.

This is really annoying because when you reach for your Analytic Visor, you reach next to your ear and hold the controller upside-down for a second, breaking your forward movement.

**Comment by JackD83** [comment]
You are sure its not a setting in NMS? I haven't played it yet, but the tracking is streamed from the HMD to steamvr as it is. There is just a minor offset correction

**Comment by RobbeSchepens** [comment]
Hm, I've done some testing and it also happens in Payday 2 VR. I also tried Virtual Desktop Streamer and there it happens as well. Yet, an official Oculus Store game, Journey of the Gods, does not do this behavior. 

Is there a possibility you could look into adding this as an optional feature/functionality?

**Comment by JackD83** [comment]
I own Payday 2, I will check it out

**Comment by tchesket** [comment]
I have been playing No Man's Sky on the official ALVR and on your forked version, and I can confirm this is happening to me as well, on this version but not on the main version. It is pretty weird.

**Comment by JackD83** [comment]
The original ALVR used FreePie to emulate the VR controllers. This was necessary to change the controller config on the fly if you only have a 3DOF headset and a limited controller. Its possible that FreePie somehow altered the Joystick input.

As I focus on the quest, I replaced FreePie with the direct emulation of the Rift S Touch controller. 
All input from the Quest goes straight into SteamVR.

You can check the input by launching SteamHome and opening the Steam Overlay. Here you can see all button presses and joystick movements. You can see that the joystick always moves in the correct direction whether you flip the controller or not.

**Comment by RobbeSchepens** [comment]
That's true. ALVR nor this fork is not to blame. I will look into asking OpenVR Advanced Settings or others to check for a solution.
