### ISSUE TITLE
"Stream Quest Microphone"

### ISSUE THREAD

**Issue by Andrew1431** [JackD83/ALVR#55]
![image](https://user-images.githubusercontent.com/9736372/66610814-b9661500-eb8a-11e9-9987-3998b1aad2c4.png)

So I've got this checked, and I use vb-cable frequently so I know how all the audio routing works, but I can't seem to actually get this setting to do anything. Is there any guide explaining how I can use the quest microphone as my mic in game? 

Excellent work on this ALVR project. I was playing some pavlov earlier and the quality is just unrivaled. Truly a great experience.

**Comment by BrotherO4** [comment]
the way i got it to work was.
open your audio settinig on window 10 and selected the input as cable output. make sure the Cable input is not disable. (it does not need to be selected. )

**Comment by JackD83** [comment]
closed due to inactivity
