### ISSUE TITLE
Issues with games played through Revive

### ISSUE THREAD

**Issue by rgferreira** [JackD83/ALVR#57]
Some Oculus exclusive games like Defector or Asgard's Wrath won't play smoothly on ALVR (other examples that run great: Robo Recall, Lone Echo). There is a quite moderate jittering in the headset tracking (not overcome by marking "-1" on the controller jittering section of the PC client).

Please don't hesitate to close this issue if you think it's not relevant.

**Comment by DannyDan** [comment]
@rgferreira how did you get past the initial setup when you need to press the right stick down?

**Comment by LoneBoco** [comment]
I experienced the same issue.  The game looks fine on the monitor but somewhere along the line it messes up.  It could be ALVR, SteamVR, or ReVive, though.  There are a lot of layers things are going through.

@DannyDan I had no problems getting passed setup.  I was using an Oculus Quest.  I was using the latest beta of SteamVR and the latest version of ReVive.  I was also using OpenVR Advanced Settings.  In the ReVive options, I disabled the trigger = grip setting so it wouldn't alter the controls.  Then, I just start SteamVR, start ALVR, and connect.  I can launch Asgard's Wrath through the ReVive panel in SteamVR.

**Comment by LoneBoco** [comment]
I also have no clue if this could be related to #51 or not.  There are certainly other issues here about low framerates on the client.

For the record, I also tried:
- h264 10mbps
- 75% video resolution
- 400kB buffer
- FFR both on/off
- Suppress frame drop on/off
- Aggressive keyframe resend on/off
- TrackingFrameOffset 0/-1

No matter what I try, I just can't get it to display smoothly.

**Comment by JorgenRe1** [comment]
Updating revive to the new pre release(you need to manually download it from revive's github) fixed the jittering and so it is perfect for me atm. Though it said in the release notes that it does not fix all issues.

Issue is not alvr related as far as I can see as if you open steam dashboard it itself is perfect whilst asgard in the background is jittery. 

Also you need for asgard to fix some controls. For that open steamvr dashboard(in vr) . Then settings. Then controller settings.

**Comment by JorgenRe1** [comment]
Download revive fix here: https://github.com/LibreVR/Revive/releases

**Comment by gunnarweibrink** [comment]
There is another update to revive (1.9.1) which completly fixes the perfromance issues, like stuttering and so on. Also they fixed the "menu button" problem with so called "chords" on the oculus controllers. Pressing A/B together (righthand, also works with X/Y lefthand) do the trick... short press for the objectives, long press for the menu.

So everything about Asgard's Wrath should work now  and it's not an issue with ALVR.
