### ISSUE TITLE
Superhot - no inputs work

### ISSUE THREAD

**Issue by MattFiler** [JackD83/ALVR#61]
When playing Superhot no inputs map, even though SteamVR detects them. 
Upon launching your hands are stuck in the floor and you cannot play.

**Comment by JackD83** [comment]
Could be the same error as #26

**Comment by Andrew1431** [comment]
Bro I gotchu, the fix is to go into the beta builds on steam, and choose one of the other betas (Sorry can't remember which one off the top of my head).

**Comment by JackD83** [comment]
closed due to inactivity
