### ISSUE TITLE
error: package ConnectionStateHolder does not exist

### ISSUE THREAD

**Issue by franMadu** [JackD83/ALVR#63]
Hi. I'm trying build the client with android studio. When I try to generate a new apk the terminal show those errors, among other mistakes which I have could resolved: 

error: package ConnectionStateHolder does not exist
error: cannot find symbol variable ConnectionStateHolder

It looks like a package or part of the code is missing or that class is no longer used. I try to search this class in Android's API but doesn't appear. I'm using api level 29.

Did someone have the same thing or know how to fix it?

![error](https://user-images.githubusercontent.com/56690611/67071942-1746be00-f184-11e9-8aa0-d181d6c7d056.png)

Thanks.

**Comment by JackD83** [comment]
Did you pull the experimental branche?

**Comment by franMadu** [comment]
Yes, the experimental

**Comment by franMadu** [comment]
Ok, I resolved it. Android studio change automatically to master branche instead experimental. I downloaded the zip file and it build at the first without problem.

Thanks for helping and great work
