### ISSUE TITLE
Errors on build

### ISSUE THREAD

**Issue by eyelykaynal** [JackD83/ALVR#65]
Sorry if I'm missing something obvious here, but I'm trying to build the latest experimental branch in VS2019. I have CUDA 10.1 and the latest Win10SDK but I'm getting the following errors. It seems to be failing on AMF and then subsequently alvr_server.
![build-errors](https://user-images.githubusercontent.com/22998865/67140092-ad034b80-f25f-11e9-800c-b317a0c778e9.png)

**Comment by FingrMastr** [comment]
Strange. Try with release profile...

**Comment by eyelykaynal** [comment]
Same result. Not sure what's going on since all the AMF files are included.

I have a 1070 anyway, so I just commented out all the AMF includes and it builds and runs fine.

**Comment by JackD83** [comment]
Can you try the latest commits please? And make sure to use the experimental branch

**Comment by eyelykaynal** [comment]
Hey man,

I will aim to do this tomorrow, time permitted.

**Comment by eyelykaynal** [comment]
Still get the stdafx.h errors and then alvr_server fails because it can't find AMF.lib

**Comment by JackD83** [comment]
I just tried to check out and build a fresh copy and it works fine. Did you try to build the whole project or single submodules? 

You have to build all submodules separately: shared, CUDA, AMF then alvr_server.

**Comment by eyelykaynal** [comment]
Yeah, I built them all separately. When building AMF I get the stdafx.h
errors and then if I try to build alvr_server it obviously fails because
AMF.lib didn't build
