### ISSUE TITLE
ALVR with no internet connection

### ISSUE THREAD

**Issue by rgferreira** [JackD83/ALVR#67]
I thought there was a difference between VD and ALVR regarding internet connection. While VD only needs internet to verify the Oculus ID, I had in mind that ALVR does not need the Internet at all. My setup is as follows: the Quest connected to a 5GHz AP which is wired (Ethernet -> USB C) to my PC, and then the Internet connection received from the router is shared to that AP. It works flawlessly with transport latency below 8ms. 

Then, I tried to disable the Internet connection to test if ALVR is working but it isn't. The PC server never shows that "Connect" button. Is this OK?

**Comment by Digeeboy** [comment]
ALVR doesn't require internet connection ... I have my Quest blocked at the router and ALVR is working fine.

**Comment by slickwarren** [comment]
@rgferreira how did you disable the internet connection?

**Comment by Digeeboy** [comment]
I disabled it on my router which has an access control panel which let's me deny Internet access based on MAC address of the client.

**Comment by rgferreira** [comment]
> @rgferreira how did you disable the internet connection?

Well, I just disabled my router. I connect my Quest to an AP wired to my PC through a Ethernet->USB-C interface. Finally, I created this issue because when I'm totally offline, sometimes the "connect" button is not visible so that I can't trigger the whole process. Finally, I got it working (did nothing though) and I can close this issue.
