### ISSUE TITLE
usb game pad with alvr plug into the quest 

### ISSUE THREAD

**Issue by jakefever191** [JackD83/ALVR#68]
i have a USB gamepad i want to uses with my quest with alvr is there a way you can make the c-type port on the quest work as USB on port or something on pc?

**Comment by JackD83** [comment]
No, that's something the android system does. You can connect a Bluetooth controller to the Quest, but alvr does not transfer that input to the PC. If you want to use a controller with alvr, get a wireless Xbox One controller and connect it directly to the PC.
