### ISSUE TITLE
Steam VR not tracking

### ISSUE THREAD

**Issue by Hydrozen** [JackD83/ALVR#69]
When I pull the trigger on my controller to launch steam vr, it opens up on my pc, but it says that it can't find the controllers and headset. My headset is still telling me to launch steam vr even though it has already opened. I'm using an Oculus Quest, and trying to get ALVR v7 to work.

Edit: Also wanted to mention that no packets are being sent which seems very odd. I have enabled access through the firewall.

**Comment by JackD83** [comment]
Try to re-install SteamVR. Something is not properly registread

**Comment by Hydrozen** [comment]
Hmm I've tried reinstalling SteamVR but it's still not working, I have virtual desktop's driver installed too. Perhaps that is conflicting with it?

**Comment by slickwarren** [comment]
@Hydrozen can you post your system info/ hardware setup and if you're using 5Ghz for your WAN connection.  Also, check the firewall settings for running steam and ALVR.  Please also comment with what you've changed in steam or ALVR settings, if any.
