### ISSUE TITLE
No mic audio and can't change steam sounds

### ISSUE THREAD

**Issue by T3ER** [JackD83/ALVR#7]
As soon as I click on any of the setting ticks the steam sounds settings can't be changed anymore. The sound is stuck on permamently. I have to delete the config file if I want to fix it temporarily.
I installed vb-cable, restarted pc and tried using the mic but I get no sound, all I see in the sound settings under quest mic options is the same message about requiring vb cable. I tried setting vb cable as my default mic. It didn't help. I do have the new versions installed. On top of that I noticed more packet loss than usual. That could be the latest oculus update so that needs more investigating. After a bit of testing I only get packet drops while mic support is enabled even if it isn't working atm.

**Comment by JackD83** [comment]
Did you get the request to access the mic on your Quest? You need to set CABLE Output as your default Microphone and something other as CABLE Input as your default audio device! I'm not sure what you mean by "steam sounds settings can't be changed" I do not change any steam settings. If you refer to the audio setting in ALVR, they can only be changed if SteamVR is not running.

I'm a little concerned by "more packet loss than usual". You should not have any packet loss at all. Streaming the mic adds another 1mbit to the streaming. If you are already at the limit of your network, this wont work well. The mic data is streamed when the checkbox is selected at the start of SteamVR, even if you can't hear it.

**Comment by T3ER** [comment]
I'm 10mbps below the limit of my router. It appears mic streaming only works for me only if I disable steam sound forcefully through config. On top of that I am indeed getting a lot more connection problems when mic and sound are enabled, not when one of them is enabled. The client loses connection or has extreme delay after working fine for 5 seconds. If drop bitrate way down it doesn't make any difference. Normally I get packet loss just every few minutes or so which isn't too bad.

**Comment by T3ER** [comment]
I think I found the problem. The router was overloaded and reducing the transmission strength to half made the connection stable at least for the 10 minutes I tested with both steam audio mic audio enabled. Both of them work at same time now too. The quest shows full connection strength. Kinda strange stuff going on but if there are not more issues after a proper test for a few hours then I call this mostly solved and useful info for future reference. The settings buttons are still not working properly though.

**Comment by JackD83** [comment]
Good to hear! You have to check the channels of your router. The default channels are very crowded in my area and I had to go to 136 5Ghz. 10mbps below the limit of the router is in general not a good idea. In reality, you are lucky if you get 2/3 of the  speed. Connection strength and throughput are different things. 

The audio settings are indeed somehow broken, I have to check it.

**Comment by T3ER** [comment]
N supports about 150mbps. For reference just having sound and 80mbps works with little to none packet loss and no connection issues. Mic and sound with same bitrate just doesn't have stable connection for me. Dropping to 55mbps made connection much more stable but the connection became more and more unstable after a few hours as indicated by the more fluctuating latency stats. The image quality tradeoff is kinda unfortunate but overall definitelly playable. Having a cooling solution for router could fix this, too. it does feel hot after a while.

**Comment by JackD83** [comment]
> N supports about 150mbps. 

Only on paper! According to this [guide](https://www.speedguide.net/faq/what-is-the-actual-real-life-speed-of-wireless-374) and my personal experience, 40-50mbit is what you get out of n. 

You should consider investing in a high quality AC router if you want to use ALVR at higher bit rates.
I'm closing this issue now and will open another one for the broker audio settings
