### ISSUE TITLE
any chance of re implementing the fake base station support?

### ISSUE THREAD

**Issue by sammiestarshine** [JackD83/ALVR#72]
hi i notice a few games i play will not register the controllers unless i use an older version of alvr that still has the fake base station support notably spectro the luigi's mansion type game but the older versions have bad stuttering and lag compared to ex 7 thanks

**Comment by JackD83** [comment]
The fake base stations are removed because the RiftS, that ALVR is emulating, has no base stations either.
Does the RiftS work with those games?

**Comment by sammiestarshine** [comment]
ah yes i see what you're saying. well funny you should say, im using virtual desktop now and i get the same issue where when i get to the main menu in spectro the controllers wont recognise (only in game, they are still connected and working outside of the game) even though virtual desktop has fake base station support so it must be an issue with the game itself. but still strange how it worked in alpha 5 version of alvr.

**Comment by JackD83** [comment]
Around the same time, oculus changed their required api for tracking. Does it still work with alpha5?
