### ISSUE TITLE
Autoload Server?

### ISSUE THREAD

**Issue by DocMAX** [JackD83/ALVR#75]
Why do i always  have to "manually" load the server? Can't it be autoloaded when SteamVR is started?

**Comment by JackD83** [comment]
Right now, the ALVR UI acts as a control panel for the SteamVR driver. That's why it needs to be loaded first. It would be possible to load the UI with the launch of SteamVR, pull requests are always welcome!

**Comment by DocMAX** [comment]
Request submitted herewith!

**Comment by JackD83** [comment]
You slightly misunderstood. A pull request is a request to me to include the solution you made. So fix the problem and I will include it in a official release :)

**Comment by DocMAX** [comment]
I think just a simple "minimize to tray" would be enough fot the moment. There are tools to convert an EXE to a service.

**Comment by jakefever191** [comment]
In the past I have tried usesing cmd and command to minimise to tray but nothing worked

**Comment by JackD83** [comment]
I added the minimized start and the server autostart. Please test!
[ALVR.exe.zip](https://github.com/JackD83/ALVR/files/4000320/ALVR.exe.zip)

**Comment by DocMAX** [comment]
Thank you. Minimize is working fine. But i think you misunderstood the "SteamVR autostart". As soon as i launch SteamVR ALVR should start automatically (minimized, via the ALVR driver). This kind of behaviour can be seen in the "Revive"-Tool and other.

**Comment by JackD83** [comment]
That's not how ALVR was designed. ALVR.exe needs to be running before you can start SteamVR and the ALVR driver. With the changes I made, you can put ALVR in autostart and SteamVR will be launched as soon as you start ALVR on the headset
