### ISSUE TITLE
Lowest latency possible for playable beat saber

### ISSUE THREAD

**Issue by NullVoxPopuli** [JackD83/ALVR#77]
Hello, this isn't an issue or feature request or anything, but more a question on config.

There are a lot of options, and I'm not really sure what most of them do.

My goal is to be able to play beat saber from steam VR with a/v sync'd and no controller lag. (Where any lag between around 40 and 100ms has significant impact on playability)

Right now it feels like I can't figure out when the game expects me to hit the blocks. It's weird.

In stepmania (ddr for computer), there is a settings area for fixing a/v sync, where it just plays a steady beat and you step on the arrows on the beat, regardless of visuals, and the game gradually adjusts until the visuals match up with what you're doing.

**Comment by MPfaffe** [comment]
I can't tell a descrete setting but:
-Decreasing the Resolution lowers encode and decode latency 
-decreasing the bitrate lowers mostly transfer latency (maybe force 60 Hz at lower bitrates to stay at better image quality, but the screen flicker uncomfortable)
-turn off the sound stream (use e.g. pc audio, BT earphones) should lower the latency
But I think it is hard to obtain constant latency < 40ms at satisfying image quality at the moment.

**Comment by NullVoxPopuli** [comment]
After playing BeatSaber a bit in both steamVR and the demo in the quest, I think the problem is with beat saber. The timing of when I should hit the blocks is different from what the game considers correct
