### ISSUE TITLE
Offset HMD head rotation in certain game

### ISSUE THREAD

**Issue by Letrange-g** [JackD83/ALVR#79]
ALVR EV8 is top-notch!
Although I noticed a weird issue, on same games, it seems like when I rotate my head and the HMD, ingame it rotates on a different pivot than my neck. Giving a weird sickening motion.
This doesn't happen when using Oculus Link or Virtual Desktop. 
Example of games doing it : 

- Rainfall Megaton, 

- A-Tech Cybernetic VR

I'm no sure why and if there is way to fix this.

**Comment by JackD83** [comment]
Does the image look warped? There is no processing of tracking data for the hmd. All tracking data is transferred 1:1 into SteamVR.

**Comment by Letrange-g** [comment]
Yes, it feels the image is warped. It's even more noticeable when tilting the head to the left or the right.

**Comment by JackD83** [comment]
Could be the same error as #31. I down't [own](https://github.com/JackD83/ALVR/wiki/My-game-is-not-working-properly!-Help!) the games and cannot check

**Comment by JackD83** [comment]
I checked Rainfall Megaton and it is indeed the same error as #31

**Comment by JackD83** [comment]
Closed and integrated in #88
