### ISSUE TITLE
Beat saber's sword incorrectly angled

### ISSUE THREAD

**Issue by orangpelupa** [JackD83/ALVR#81]
Maybe around 30 degrees tilted too high.
I used beat Saber from steam.

Maybe add controller offset option?

 Other people suggested to use openvr input emulator offset but that plugin hasn't been updated for years and I can't get the offset to work .

Workaround : Physically rotate the controller 180 degrees so the trigger become on your thumb. Grip it that way. The swords will be good

**Comment by JackD83** [comment]
With the latest ev8 from this fork? The 30° offset was fixed a long time ago with the first release.

**Comment by orangpelupa** [comment]
Yeah, the it's same with relive vr.

The touch controllers itself are fine tho as the swords in the beat Saber quest demo are angled properly.

Any diagnostics I can look at?

**Comment by JackD83** [comment]
I just checked the controller in beat saber. I don't see any issue with ev8. Sticks are aligned with the controller handle
![beat](https://user-images.githubusercontent.com/15889805/69725903-9209de00-111f-11ea-8c96-19545037499e.png)

**Comment by orangpelupa** [comment]
Hi again Jack. 

Tried on a different computer with different hardware (now its running on gtx 1660)

Same issue, the swords are angled too high.

Could I ask for a feature request? (add angle correction/offset box in ALVR)

**Comment by orangpelupa** [comment]
The swords are not supposed to align with oculus quest handle but with its upper handle. I'll add a pic after I finish taking a bath

**Comment by orangpelupa** [comment]
jack, sorry! turns out it was my fault

1. I misunderstood the angle of "grab" in oculus quest
2. Beat Saber on Steam VR have incorrect scale (everything looks waaaay too big)

after I fixed my mindset of the "correct" angle (thanks to your picture) and holding the controller lower (grabbing the handle, no thumbs on the sticks), my brain accepted the angle.

after i set IPD offset manually thru http://localhost:27062/console/index.html with this command "settings steamvr.ipdOffset 0.0060"

its even better now.

so for those feeling weird with beat saber's swords, try doing those 2 tings. ALVR already works good.
