### ISSUE TITLE
Sometimes the HMD display freezes

### ISSUE THREAD

**Issue by sok0** [JackD83/ALVR#82]
Starting an issue but might not have enough info to figure out what is going on yet.

Sometimes while in game the headset picture freezes. I haven't figured out what is causing this yet which will require more testing to figure out. It might be related to the main game window running on the desktop losing focus.

Some things that happen when the HMD picture freezes:
The desktop game window still runs normally and orientation of the view etc are updated as normal as if it is still tracking the quest movement
The Quest power button loses functionality -- if the power button is held down nothing happens
If the power button is pressed quickly the unit will go to sleep but will not come out of sleep
The Controllers are unable to pause the game, i.e. cannot exit ALVR

Some things that I have tried that worked:
I was able to click around on the desktop and the headset started working again
If the game is closed then ALVR will go back to the CONNECT screen

I will do some more testing and update if I figure out more what is going on.

**Comment by MPfaffe** [comment]
which Version of ALVR do you use? 

with experimental v8 and default settings of the video buffer the problem should not occur
