### ISSUE TITLE
Audio lag on i5-4460 + GTX 1660 Super

### ISSUE THREAD

**Issue by orangpelupa** [JackD83/ALVR#83]
hiya! 
I got a pretty noticeable audio lag with
- Win 10 1909
- intel i5 4460
- GTX 1660 super
- ALVR v8 HEVC

But i have NO NOTICEABLE audio lag with
- WIN10 1903
- ASUS rog 702zc
- Ryzen 7 1700
- RX580
- ALVR v8 HEVC

Lag are noticeable in
1. On desktop (with no steam home running, just steam vr) Windows sound setting. Click the volume mixer slider, the DING sound will come late (PC speaker, then noticeably late-- Quest speaker)
2. Beat saber (the music and block slicing SFX will come late)

I have not tried other games.
I have not tried Oculus Link (no free space on C:)

The video stream itself is as responsive as usual. no issue.

**Comment by HolyCaonima** [comment]
Also happened on mine GTX1060 ALVR v7 HEVC

**Comment by orangpelupa** [comment]
i think i may found the culprit.

The audio lag only happen AFTER the stream got blocky and the game "froze" for a split second (steam VR floating logo says please wait).

everything works fine if you restart steam vr again. 

maybe related to CPU overburden?

**Comment by JackD83** [comment]
Please check if you PC is fast enough to play the game at 72Fps. If you PC is struggling in some scenes, such error can occur. You can try to lower the SteamVR super-sampling by switching to manually. 
There will always be a noticeable audio delay and games like Beat saber will never be perfect with a streaming solution

**Comment by orangpelupa** [comment]
> Please check if you PC is fast enough to play the game at 72Fps. If you PC is struggling in some scenes, such error can occur. You can try to lower the SteamVR super-sampling by switching to manually.
> There will always be a noticeable audio delay and games like Beat saber will never be perfect with a streaming solution

yeah the game runs 72fps and the steamvr frametime indicator is stable. 

anyway, the audio lag will be gone when ALVR on Quest was closed and launched again.

**Comment by Sztrovacsek81** [comment]
I also had a huge audio delay (maybe 500-1000ms). Turned off the audio stream and using a bluetooth headset instead solved my problem. Now I'm able to finish in top 10 almost in every song under Dance Collider while streaming through ALVR! Nicely done JackD83!
