### ISSUE TITLE
Request: an option to fake Quest as Vive

### ISSUE THREAD

**Issue by orangpelupa** [JackD83/ALVR#86]
because some games have problem detecting some buttons or the whole controller altogether. But works fine when Quest was reported as VIVE (at least when tested via AMD ReLive VR that allows Quest to be reported as CV1 or as VIVE)

**Comment by JackD83** [comment]
Short answer is no. While this could be done (and ReLive does it), the controller of the Quest can be perfectly mapped to the Rift-S controller without any issues. Implementing an Vive wand emulation would always come with some kind of mapping, which could work well for some games and not for others. Walking by pressing the upper touchpad is one example, its just horrible with the joystick. SteamVR provides a perfect way of handling this (SteamVR Input) but it has to be supported by the game.

If the game supports the Rift-S and is not working with ALVR -> bug in ALVR, if the game does not support the rift, ask the developers to add support for SteamVR Input
