### ISSUE TITLE
Warped image after Oculus API change

### ISSUE THREAD

**Issue by JackD83** [JackD83/ALVR#88]
Some games produce a warped image after oculus changed its required API beginning with Oculus Version 9. The result looks like the field of view is way to large.

The distortion is caused by the required `<uses-feature android:name="android.hardware.vr.headtracking" android:required="true" android:version="1"/>`

in the client manifest to enable controller tracking on later firmware versions

Known broken games are:
- DCS World
- Rise of the Tomb Raider
- Rainfall Megaton
- A-Tech Cybernetic VR

After the change from oculus, the reported fov changed from:
`GetProjectionRaw Eye=0 (l,r,t,b)=(45.000000,45.000000,45.000000,45.000000)`
to
`GetProjectionRaw Eye=0 (l,r,t,b)=(52.000000,42.000000,53.000000,47.000004)`

I tried to change it back manually, but this parameters change the rendering on the quest and forcing it to the old values did not help

**Comment by zarik5** [comment]
Found the fix! #102 Before I proceed with the fix, I want to know: is DCS the only one that require the tracking system string to be changed? Is a "Emulate Vive headset" option enough or is it better to allow the user to set custom strings for tracking system, serial number, model number, etc... ? It happens that when I substitute all Oculus S strings with Vive ones (taken from polygraphene's repo), when I disable the controllers and I use a gamepad, in the SteamVR house the gaze pointer no longer works so I cannot teleport and cannot use the UI. But when using the controllers everything seems fine.

**Comment by JackD83** [comment]
Maybe we should add the Vive as emulated headset like the Rift S Controller Mode in the other tab. 
At first I was thinking that the faulty games should be fixed, but I realize now that that will never happen

**Comment by JackD83** [comment]
@eyelykaynal please test ev9 with DCS World

@Letrange-g can you please test your games; Rainfall Megaton and A-Tech Cybernetic VR with ev9 and the warp fix? I'm not sure how Rainfall Megaton should look like and I can't play it for long without motion sickness

**Comment by eyelykaynal** [comment]
Hey man,

I will aim to do this tomorrow, time permitted.

**Comment by eyelykaynal** [comment]
This is working quite well now. The warping is gone but the cockpit looks a little jittery when looking around. This could possibly fixed with some tweaking of the settings though, I will let you know when I've had a chance to try.

Nice work!
