### ISSUE TITLE
Experimental 8 Not Launching with Steam VR (1.8.21)

### ISSUE THREAD

**Issue by thechanman97** [JackD83/ALVR#90]
Hi,

All steps leading up to the actual booting of Steam VR are fine, except that when it comes time to hitting "Start Server," Steam VR keeps booting up in safe mode and cannot detect my headset. When I proceed to start the server via the Quest triggers, it gives me this error: "An error occurred while updating SteamVR (app already running)." ALVR also gives me an error saying that  my GPU does not support NVENC, but it does.

I am using a GTX 1060M, on an Oculus Quest, and have downloaded VC 2019. There is also only one ALVR driver installed.

Is there an extra step I am missing? 

P.S. Experimental 7 works just fine, except certain games like Boneworks does not work in that earlier version.

Thank you.

**Comment by codewing** [comment]
I'm having the same issue, steamvr 1.8.21 and 1.9.12 beta both don't show connected headsets.

**Comment by JackD83** [comment]
There are no fundamental changes in v7 to v8 other than the new visual studio version. 

@thechanman97 the error that your gpu does not support NVEC prevents the driver to load and puts SteamVR in save mode. With a GTX 1060M, I suspect that you are on a Laptop. Can you please try to disable your Intel graphics card? It could be that the new build is choosing the wrong card at random

@codewing Your SteamVR is starting up?

**Comment by codewing** [comment]
Yes SteamVR is starting.
I don't have a headset with me but could force starting the "alvr.exe" with the nvidia gpu make a difference? Because the built binary of the original repos works without any additional steps.

**Comment by JackD83** [comment]
Its not ALVR.exe that needs to be set on the NVIDIA gpu but steamvr itself. It could be that the gpu enumeration is random und with previous versions of ALVR you got lucky.

Please try to disable the intel gpu for a test

**Comment by codewing** [comment]
Sorry for the extremely late reply.
I've tried it with the latest version now but it still doesn't work.
![image](https://user-images.githubusercontent.com/12066466/74666464-d3031300-51a1-11ea-9ac6-a1df8c1984dd.png)
![image](https://user-images.githubusercontent.com/12066466/74666528-f463ff00-51a1-11ea-8e9a-b2ae14db810c.png)

**Comment by KomputerWhiz** [comment]
i have a similar issue and also found that v7 worked aswell, i was thinking it had something to do with the keplar architeture of my gpu, given the legacy status of drivers in 2019 but it would apear its even affecting 10 series cards. my issues started at the same time as well with v8 and has proceeded onto v9
