### ISSUE TITLE
controller has problem with boneworks

### ISSUE THREAD

**Issue by HolyCaonima** [JackD83/ALVR#93]

**Comment by Mr-FizzleWizzle** [comment]
I am having the same issue. the controllers are floating too far away. Looks like it picks it up as Vive Controllers.

**Comment by TheLo1411** [comment]
Same issue here, only boneworks seems to have this problem. Controllers work fine, their position is off by about 10-15 cm and their rotation is also wrong by 45 degrees .

**Comment by Coolguy1260** [comment]
same issue, just bought boneworks but controllers are off

**Comment by JackD83** [comment]
There is a description how to fix ALVR for Boneworks
https://steamcommunity.com/sharedfiles/filedetails/?id=1980632821

Question remains, why is only boneworks affected? I could add a workaround fix for Boneworks

**Comment by fridgy** [comment]
JackD83,

I created the guide you linked to. Would it be possible to just have a portion of the GUI where you could set the controller offsets (with the default being what ALVR uses standard)? Or maybe there could be offset profiles. I looked into this but since it's driver related I wasn't really sure how to adjust those on the fly.

As for the issue, I'm not sure why Boneworks is broken but my theory was that Boneworks has its own offsets set and they either conflict with or are added on top of the existing offsets. That's just my best guess, honestly, but thought I'd weigh in.

**Comment by TheLo1411** [comment]
First of all, thanks guys for the replies and the solution. I second @fridgy , it could be a nice addition to ALVR being able to dynamically customize the controller offsets

**Comment by JackD83** [comment]
Controller offset can be updated on the fly. I'm not sure if its a good idea to allow complete free adjustments as people tend to play with it and then complain if it breaks something. 

Maybe a new tab with game specific fixes could be done.

As for the cause of the problem, my guess is, that boneworks never runs on openvr if its played with the rift s. It probably using the oculus sdk for that and breaks if we fake a rift s in openvr. Link is using oculus sdk and seems to be fine

**Comment by fridgy** [comment]
Either option would be great. If you did implement offset control, a "Return to Default" button may help with some of that.

**Comment by bubufofo** [comment]
@fridgy can you please share the boneworks build please? thanks

**Comment by fridgy** [comment]
I'm not in a place where I could get that on GitHub but you can check here for instructions/a build that fixes the issue mostly. https://www.reddit.com/r/OculusQuest/comments/ewbwwy/alvr_boneworks_tracking_issue_fixed_hand_tilt_and/

**Comment by zarik5** [comment]
I can make a pull request with an optional fix. Is it just Boneworks that has this problem? Could ALVR benefit from a configurable rotation and translation offset?

**Comment by zarik5** [comment]
I can make a pull request with the optional fix. Is it just Boneworks that has this problem? The idea is to add a configurable rotation and translation offset for the controllers and to add a new tab with buttons for game specific fixes (that act as presets for other settings).

**Comment by JackD83** [comment]
@zarik5 I think there are some more games that have problems in general. The most important part would be the live update of the parameters without restarting the streaming.

**Comment by zarik5** [comment]
> The most important part would be the live update of the parameters without restarting the streaming.

This would need a bit more coding and testing. In the mean time I'm doing the Presets tab.

**Comment by LVollmilch** [comment]
> I can make a pull request with the optional fix. Is it just Boneworks that has this problem? The idea is to add a configurable rotation and translation offset for the controllers and to add a new tab with buttons for game specific fixes (that act as presets for other settings).

It's actually not only Boneworks. Maybe this will help you figure it out:
 
Dunno if anyone has that issue too, but in SteamVR Home the controllers are set off and on sticks just like Boneworks (exactly same offset, and exactly like boneworks, the pointer (to select something on the Screens ingame infront of you) IS NOT set off). They apparantly get their values somewhere else but from the same source. Except for the pointers, they work correctly.

As for other games (Blades & Sorcery, The Lab, small games, etc.) I never experienced issues, but I'm new to VR so couldn't test that much.

Also while taking the screenshots I noticed, that the gadgets seems to be in the right place (as seen in screenshot). Strange. Hope this helps.

![Hands On Sticks BONEWORKS 1](https://user-images.githubusercontent.com/52360154/76160811-989bee80-612d-11ea-9b85-1904b75525c6.jpg)
![Hands On Sticks BONEWORKS 2](https://user-images.githubusercontent.com/52360154/76160812-99348500-612d-11ea-8470-c3326ab06651.jpg)
![Hands On Sticks SteamVR Home](https://user-images.githubusercontent.com/52360154/76160810-976ac180-612d-11ea-9e97-799429b3a98a.jpg)
![Real Life Position](https://user-images.githubusercontent.com/52360154/76160807-95a0fe00-612d-11ea-97f3-1189dbdd6bc0.PNG)
![Gagdet SteamVR Home Offset](https://user-images.githubusercontent.com/52360154/76160802-920d7700-612d-11ea-882a-e5b15ec6e4cb.PNG)

**Comment by JackD83** [comment]
Continue in #135
