### ISSUE TITLE
ALVR Client won't load and keeps crashing

### ISSUE THREAD

**Issue by Lemon64k** [JackD83/ALVR#94]
im so fucking mad,this morning it was workin fine then for some reason it stopped working,i keep getting the 3 dots indicating it's loading but it goes on forever and when i close it it says it stopped working,i reinstalled twice now and it won't work,pls help
EDIT this can be fixed by making sure alvr's server isn't open,if it is,reinstall the alvr server and it'll work

**Comment by JackD83** [comment]
So this issue is resolved?

**Comment by Lemon64k** [comment]
Yes it is,weird how it happened tho
