### ISSUE TITLE
Failed to start audio capture

### ISSUE THREAD

**Issue by Abahu** [JackD83/ALVR#97]
Failed to start audio capture. Thread aborted before starting to loopback capture. message=IAudioClient::Initialize failed: hr = 0x88890008

I'm having the same issue that other people have mentioned before. I'm using Experimental v8. Starting the server with Steam Sound checked causes a crash and then starts SteamVR in safe mode, where it won't work with ALVR. Unchecking Steam Sound fixes the error, but you can't play horror games without sound.

I have already installed the latest drivers for my audio device, which is Realtek. I do not have any USB device plugged in besides my keyboard and mouse. I do not have any speakers for my computer, however. I have tried plugging in and using my headset (USB and non-USB) along with not using my headset.

**Comment by JackD83** [comment]
its the same error as #45
