### ISSUE TITLE
The audio is very sizzle

### ISSUE THREAD

**Issue by BeSseR89** [JackD83/ALVR#98]
It's very interesting and I don't know why is happening(sizzle/cracking) when streaming audio... For example riftcat working perfectly... so theorically the problem isn't my hardware.

**Comment by midorikuma** [comment]
Some here. I want to know the solution too.

**Comment by JackD83** [comment]
> so theorically the problem isn't my hardware.

I'm not so sure about that. I have those too sometimes, but I also get them in other applications and on different Quest
